import { describe, expect, it } from 'vitest';
import {
  JALALI_YEAR_MAX,
  JALALI_YEAR_MIN,
  gregorianToJalali,
  isJalaliLeapYear,
  isJalaliYearInProductRange,
  isValidJalaliDate,
  jalaliMonthLength,
  jalaliToGregorianIso,
  jalaliYearContainingIso,
} from './jalali';

/**
 * Fixed Jalali → Gregorian fixtures. Independently confirmed against the ICU
 * `persian` calendar (the same source the FA display formatter already uses),
 * not generated by this module's own round trip.
 */
const FIXTURES: Array<[jalali: [number, number, number], iso: string]> = [
  // Jalali new year (1 Farvardin) always lands on the March equinox day.
  [[1378, 1, 1], '1999-03-21'],
  [[1400, 1, 1], '2021-03-21'],
  [[1404, 1, 1], '2025-03-21'],
  [[1405, 1, 1], '2026-03-21'],
  [[1406, 1, 1], '2027-03-21'],
  // Mid-year (31-day months Farvardin–Shahrivar).
  [[1405, 6, 25], '2026-09-16'],
  [[1405, 7, 1], '2026-09-23'],
  [[1405, 7, 15], '2026-10-07'],
  [[1405, 7, 20], '2026-10-12'],
  [[1405, 7, 25], '2026-10-17'],
  // End of year (30-day months Mehr–Bahman, then Esfand).
  [[1405, 11, 30], '2027-02-19'],
  [[1405, 12, 29], '2027-03-20'],
  // Leap-sensitive Esfand 30 (leap years only).
  [[1399, 12, 30], '2021-03-20'],
  [[1403, 12, 30], '2025-03-20'],
  [[1408, 12, 30], '2030-03-20'],
  // Non-leap year ends on Esfand 29.
  [[1404, 12, 29], '2026-03-20'],
  // Supported-horizon edges.
  [[1478, 12, 29], '2100-03-19'],
];

describe('Jalali ↔ Gregorian conversion', () => {
  it('converts fixed known fixtures to exact Gregorian ISO', () => {
    for (const [[jy, jm, jd], iso] of FIXTURES) {
      expect(jalaliToGregorianIso(jy, jm, jd)).toBe(iso);
    }
  });

  it('converts fixed fixtures back to the same Jalali civil date', () => {
    for (const [[jy, jm, jd], iso] of FIXTURES) {
      const [gy, gm, gd] = iso.split('-').map(Number) as [
        number,
        number,
        number,
      ];
      expect(gregorianToJalali(gy, gm, gd)).toEqual({
        year: jy,
        month: jm,
        day: jd,
      });
    }
  });

  it('rejects invalid months and days instead of normalizing them', () => {
    expect(jalaliToGregorianIso(1405, 13, 1)).toBeNull();
    expect(jalaliToGregorianIso(1405, 0, 1)).toBeNull();
    expect(jalaliToGregorianIso(1405, 6, 32)).toBeNull();
    expect(jalaliToGregorianIso(1405, 6, 0)).toBeNull();
    expect(jalaliToGregorianIso(1405, 7, 31)).toBeNull();
    expect(jalaliToGregorianIso(1405, 1, 1.5)).toBeNull();
  });

  it('applies Jalali month lengths', () => {
    for (let month = 1; month <= 6; month += 1) {
      expect(jalaliMonthLength(1405, month)).toBe(31);
    }
    for (let month = 7; month <= 11; month += 1) {
      expect(jalaliMonthLength(1405, month)).toBe(30);
    }
    expect(jalaliMonthLength(1405, 12)).toBe(29);
    expect(jalaliMonthLength(1403, 12)).toBe(30);
    expect(jalaliMonthLength(1405, 13)).toBe(0);
    expect(jalaliMonthLength(1405, 0)).toBe(0);
  });

  it('accepts Esfand 30 only in leap years', () => {
    // ICU-confirmed leap years in the supported horizon.
    expect(isJalaliLeapYear(1399)).toBe(true);
    expect(isJalaliLeapYear(1403)).toBe(true);
    expect(isJalaliLeapYear(1408)).toBe(true);
    expect(isJalaliLeapYear(1404)).toBe(false);
    expect(isJalaliLeapYear(1405)).toBe(false);
    expect(isJalaliLeapYear(1406)).toBe(false);
    expect(isJalaliLeapYear(1407)).toBe(false);

    expect(isValidJalaliDate(1403, 12, 30)).toBe(true);
    expect(jalaliToGregorianIso(1403, 12, 30)).toBe('2025-03-20');
    expect(isValidJalaliDate(1404, 12, 30)).toBe(false);
    expect(jalaliToGregorianIso(1404, 12, 30)).toBeNull();
    expect(isValidJalaliDate(1405, 12, 30)).toBe(false);
    expect(jalaliToGregorianIso(1405, 12, 30)).toBeNull();
    // Esfand 29 stays valid in both.
    expect(jalaliToGregorianIso(1404, 12, 29)).toBe('2026-03-20');
    expect(jalaliToGregorianIso(1403, 12, 29)).toBe('2025-03-19');
  });

  it('bounds the ASK-supported Jalali horizon to the Gregorian 20xx horizon', () => {
    expect(JALALI_YEAR_MIN).toBe(1378);
    expect(JALALI_YEAR_MAX).toBe(1478);
    expect(isJalaliYearInProductRange(1405)).toBe(true);
    expect(isJalaliYearInProductRange(1378)).toBe(true);
    expect(isJalaliYearInProductRange(1478)).toBe(true);
    expect(isJalaliYearInProductRange(1377)).toBe(false);
    expect(isJalaliYearInProductRange(1479)).toBe(false);
    // Gregorian years must never look like supported Jalali years.
    expect(isJalaliYearInProductRange(2026)).toBe(false);
    expect(isJalaliYearInProductRange(1999)).toBe(false);
  });

  it('reports the Jalali year containing a Gregorian ISO date', () => {
    // Jalali year boundary is 21 March.
    expect(jalaliYearContainingIso('2026-03-20')).toBe(1404);
    expect(jalaliYearContainingIso('2026-03-21')).toBe(1405);
    expect(jalaliYearContainingIso('2026-09-16')).toBe(1405);
    expect(jalaliYearContainingIso('2026-12-31')).toBe(1405);
    expect(jalaliYearContainingIso('2027-01-01')).toBe(1405);
    expect(jalaliYearContainingIso('2027-03-21')).toBe(1406);
    expect(jalaliYearContainingIso('not-a-date')).toBeNull();
  });
});
