import type { GuidedQuestion } from './types';

export const GUIDED_QUESTIONS: GuidedQuestion[] = [
  // ── Career & Work ───────────────────────────────────────────────────────────
  {
    id: 'job-interview',
    categoryId: 'career-work',
    actionType: 'job_interview',
    needsTime: true,
    labels: {
      en: 'Job interview',
      fa: 'مصاحبه کاری',
      ru: 'Собеседование',
      ar: 'مقابلة عمل',
    },
  },
  {
    id: 'send-resume',
    categoryId: 'career-work',
    actionType: 'job_application',
    needsTime: false,
    labels: {
      en: 'Send a resume or job application',
      fa: 'ارسال رزومه یا درخواست شغل',
      ru: 'Отправить резюме',
      ar: 'إرسال السيرة الذاتية',
    },
  },
  {
    id: 'career-focus-week',
    categoryId: 'career-work',
    actionType: 'career_focus',
    needsTime: false,
    labels: {
      en: 'What should I focus on in my career this week?',
      fa: 'این هفته روی چه چیزی در مسیر شغلی‌ام تمرکز کنم؟',
      ru: 'На чём мне сфокусироваться в карьере на этой неделе?',
      ar: 'على ماذا يجب أن أركّز في مسيرتي المهنية هذا الأسبوع؟',
    },
  },
  {
    id: 'ask-raise',
    categoryId: 'career-work',
    actionType: 'salary_negotiation',
    needsTime: true,
    labels: {
      en: 'Ask for a raise or salary review',
      fa: 'درخواست افزایش حقوق یا بازبینی حقوق',
      ru: 'Попросить повышение или пересмотр зарплаты',
      ar: 'طلب زيادة أو مراجعة الراتب',
    },
  },
  {
    id: 'negotiate-offer',
    categoryId: 'career-work',
    actionType: 'offer_negotiation',
    needsTime: true,
    labels: {
      en: 'Negotiate a job offer',
      fa: 'مذاکره روی پیشنهاد شغلی',
      ru: 'Обсудить условия предложения о работе',
      ar: 'التفاوض على عرض عمل',
    },
  },
  {
    id: 'start-new-job',
    categoryId: 'career-work',
    actionType: 'job_start',
    needsTime: true,
    labels: {
      en: 'Start a new job or role',
      fa: 'شروع شغل یا نقش جدید',
      ru: 'Начать новую работу или роль',
      ar: 'بدء وظيفة أو دور جديد',
    },
  },
  {
    id: 'quit-job',
    categoryId: 'career-work',
    actionType: 'job_resignation',
    needsTime: false,
    labels: {
      en: 'Resign or leave a job',
      fa: 'استعفا یا ترک شغل',
      ru: 'Уволиться или уйти с работы',
      ar: 'الاستقالة أو ترك الوظيفة',
    },
  },
  {
    id: 'ask-promotion',
    categoryId: 'career-work',
    actionType: 'promotion_request',
    needsTime: true,
    labels: {
      en: 'Ask for a promotion',
      fa: 'درخواست ارتقای شغلی',
      ru: 'Попросить повышение по должности',
      ar: 'طلب ترقية',
    },
  },

  // ── Love & People ───────────────────────────────────────────────────────────
  {
    id: 'reconcile',
    categoryId: 'relationships',
    actionType: 'reconciliation',
    needsTime: true,
    labels: {
      en: 'Reconcile after a fight',
      fa: 'آشتی بعد از دعوا',
      ru: 'Примириться после ссоры',
      ar: 'المصالحة بعد شجار',
    },
  },
  {
    id: 'hard-talk',
    categoryId: 'relationships',
    actionType: 'difficult_conversation',
    needsTime: true,
    labels: {
      en: 'Have a difficult conversation',
      fa: 'داشتن یک گفتگوی سخت',
      ru: 'Провести трудный разговор',
      ar: 'إجراء محادثة صعبة',
    },
  },
  {
    id: 'first-date',
    categoryId: 'relationships',
    actionType: 'first_meeting',
    needsTime: true,
    labels: {
      en: 'First date or first meeting',
      fa: 'اولین قرار یا اولین ملاقات',
      ru: 'Первое свидание или первая встреча',
      ar: 'موعد أول أو لقاء أول',
    },
  },
  {
    id: 'propose',
    categoryId: 'relationships',
    actionType: 'marriage_proposal',
    needsTime: true,
    labels: {
      en: 'Propose marriage',
      fa: 'پیشنهاد ازدواج',
      ru: 'Сделать предложение',
      ar: 'تقديم عرض زواج',
    },
  },
  {
    id: 'end-relationship',
    categoryId: 'relationships',
    actionType: 'relationship_ending',
    needsTime: false,
    labels: {
      en: 'End a relationship',
      fa: 'پایان دادن به یک رابطه',
      ru: 'Завершить отношения',
      ar: 'إنهاء علاقة',
    },
  },
  {
    id: 'strengthen-relationship',
    categoryId: 'relationships',
    actionType: 'relationship_strength',
    needsTime: false,
    labels: {
      en: 'How can I strengthen an important relationship right now?',
      fa: 'چطور می‌توانم یک رابطه مهم را همین حالا تقویت کنم؟',
      ru: 'Как укрепить важные отношения прямо сейчас?',
      ar: 'كيف أقوّي علاقة مهمة الآن؟',
    },
  },
  {
    id: 'family-gathering',
    categoryId: 'relationships',
    actionType: 'family_gathering',
    needsTime: true,
    labels: {
      en: 'Plan or attend a family gathering',
      fa: 'برنامه‌ریزی یا شرکت در دورهمی خانوادگی',
      ru: 'Запланировать или посетить семейную встречу',
      ar: 'تخطيط أو حضور تجمع عائلي',
    },
  },
  {
    id: 'apologize',
    categoryId: 'relationships',
    actionType: 'apology',
    needsTime: true,
    labels: {
      en: 'Apologize or make amends',
      fa: 'عذرخواهی یا جبران',
      ru: 'Извиниться или загладить вину',
      ar: 'الاعتذار أو التكفير',
    },
  },

  // ── Money & Business ────────────────────────────────────────────────────────
  {
    id: 'launch-project',
    categoryId: 'money-business',
    actionType: 'business_launch',
    needsTime: true,
    labels: {
      en: 'Best time to launch a new project or product',
      fa: 'بهترین زمان برای لانچ پروژه یا محصول جدید',
      ru: 'Лучшее время для запуска нового проекта или продукта',
      ar: 'أفضل وقت لإطلاق مشروع أو منتج جديد',
    },
  },
  {
    id: 'sign-contract',
    categoryId: 'money-business',
    actionType: 'contract_signing',
    needsTime: true,
    labels: {
      en: 'Best time to sign a contract',
      fa: 'بهترین زمان برای امضای قرارداد',
      ru: 'Лучшее время для подписания контракта',
      ar: 'أفضل وقت لتوقيع عقد',
    },
  },
  {
    id: 'apply-loan',
    categoryId: 'money-business',
    actionType: 'loan_application',
    needsTime: false,
    labels: {
      en: 'Apply for a loan or credit line',
      fa: 'درخواست وام یا اعتبار مالی',
      ru: 'Подать заявку на кредит',
      ar: 'التقدم بطلب قرض أو ائتمان',
    },
  },
  {
    id: 'buy-sell-asset',
    categoryId: 'money-business',
    actionType: 'asset_trade',
    needsTime: true,
    labels: {
      en: 'Buy or sell stocks, gold, or crypto',
      fa: 'خرید یا فروش سهام، طلا یا کریپتو',
      ru: 'Купить или продать акции, золото или крипту',
      ar: 'شراء أو بيع الأسهم أو الذهب أو الكريبتو',
    },
  },
  {
    id: 'meet-investor',
    categoryId: 'money-business',
    actionType: 'investor_meeting',
    needsTime: true,
    labels: {
      en: 'Meet an investor or pitch for funding',
      fa: 'جلسه با سرمایه‌گذار یا ارائه برای جذب سرمایه',
      ru: 'Встреча с инвестором или питч',
      ar: 'لقاء مستثمر أو عرض للتمويل',
    },
  },
  {
    id: 'price-increase',
    categoryId: 'money-business',
    actionType: 'pricing_change',
    needsTime: false,
    labels: {
      en: 'Raise prices or change pricing',
      fa: 'افزایش قیمت یا تغییر تعرفه',
      ru: 'Повысить цены или изменить тарифы',
      ar: 'رفع الأسعار أو تغيير التسعير',
    },
  },
  {
    id: 'hire-employee',
    categoryId: 'money-business',
    actionType: 'hiring',
    needsTime: true,
    labels: {
      en: 'Hire a key employee or partner',
      fa: 'استخدام کارمند یا شریک کلیدی',
      ru: 'Нанять ключевого сотрудника или партнёра',
      ar: 'توظيف موظف أو شريك رئيسي',
    },
  },
  {
    id: 'close-deal',
    categoryId: 'money-business',
    actionType: 'deal_closing',
    needsTime: true,
    labels: {
      en: 'Close an important business deal',
      fa: 'بستن یک معامله مهم تجاری',
      ru: 'Закрыть важную сделку',
      ar: 'إبرام صفقة تجارية مهمة',
    },
  },

  // ── Health & Body ───────────────────────────────────────────────────────────
  {
    id: 'surgery',
    categoryId: 'health-wellness',
    actionType: 'surgery',
    needsTime: true,
    labels: {
      en: 'Schedule a surgery',
      fa: 'برنامه‌ریزی برای جراحی',
      ru: 'Запланировать операцию',
      ar: 'تحديد موعد عملية جراحية',
    },
  },
  {
    id: 'start-fast',
    categoryId: 'health-wellness',
    actionType: 'fasting_start',
    needsTime: false,
    labels: {
      en: 'Start a fast or detox diet',
      fa: 'شروع روزه یا رژیم پاکسازی',
      ru: 'Начать пост или детокс',
      ar: 'بدء صيام أو حمية تطهير',
    },
  },
  {
    id: 'dentist',
    categoryId: 'health-wellness',
    actionType: 'dental_visit',
    needsTime: true,
    labels: {
      en: 'Visit the dentist',
      fa: 'مراجعه به دندان‌پزشک',
      ru: 'Визит к стоматологу',
      ar: 'زيارة طبيب الأسنان',
    },
  },
  {
    id: 'fertility',
    categoryId: 'health-wellness',
    actionType: 'fertility_treatment',
    needsTime: false,
    labels: {
      en: 'Fertility treatment or IVF cycle',
      fa: 'درمان ناباروری یا چرخه IVF',
      ru: 'Лечение бесплодия или ЭКО',
      ar: 'علاج الخصوبة أو دورة التلقيح الصناعي',
    },
  },
  {
    id: 'start-workout',
    categoryId: 'health-wellness',
    actionType: 'workout_routine',
    needsTime: false,
    labels: {
      en: 'Start a new workout routine',
      fa: 'شروع برنامه تمرینی جدید',
      ru: 'Начать новую программу тренировок',
      ar: 'بدء روتين تمارين جديد',
    },
  },
  {
    id: 'therapy-session',
    categoryId: 'health-wellness',
    actionType: 'therapy_session',
    needsTime: true,
    labels: {
      en: 'Start therapy or a counseling session',
      fa: 'شروع درمان یا جلسه مشاوره',
      ru: 'Начать терапию или консультацию',
      ar: 'بدء العلاج أو جلسة استشارة',
    },
  },
  {
    id: 'medical-checkup',
    categoryId: 'health-wellness',
    actionType: 'medical_checkup',
    needsTime: false,
    labels: {
      en: 'Schedule a medical checkup',
      fa: 'برنامه‌ریزی برای معاینه پزشکی',
      ru: 'Запланировать медосмотр',
      ar: 'تحديد موعد فحص طبي',
    },
  },
  {
    id: 'start-meditation',
    categoryId: 'health-wellness',
    actionType: 'meditation_practice',
    needsTime: false,
    labels: {
      en: 'Start a meditation or mindfulness practice',
      fa: 'شروع مدیتیشن یا تمرین ذهن‌آگاهی',
      ru: 'Начать медитацию или практику осознанности',
      ar: 'بدء ممارسة التأمل أو اليقظة',
    },
  },

  // ── Travel & Place ──────────────────────────────────────────────────────────
  {
    id: 'start-trip',
    categoryId: 'travel-place',
    actionType: 'travel_start',
    needsTime: true,
    labels: {
      en: 'Start a journey',
      fa: 'شروع یک سفر',
      ru: 'Начать поездку',
      ar: 'بدء رحلة',
    },
  },
  {
    id: 'business-trip',
    categoryId: 'travel-place',
    actionType: 'business_trip',
    needsTime: false,
    labels: {
      en: 'Take a business trip',
      fa: 'سفر کاری',
      ru: 'Деловая поездка',
      ar: 'رحلة عمل',
    },
  },
  {
    id: 'relocate-city',
    categoryId: 'travel-place',
    actionType: 'relocation',
    needsTime: false,
    labels: {
      en: 'Move to a new city or country',
      fa: 'مهاجرت به شهر یا کشور جدید',
      ru: 'Переехать в новый город или страну',
      ar: 'الانتقال إلى مدينة أو دولة جديدة',
    },
  },
  {
    id: 'buy-sell-property',
    categoryId: 'travel-place',
    actionType: 'property_trade',
    needsTime: true,
    labels: {
      en: 'Buy or sell property',
      fa: 'خرید یا فروش ملک',
      ru: 'Купить или продать недвижимость',
      ar: 'شراء أو بيع عقار',
    },
  },
  {
    id: 'sign-lease',
    categoryId: 'travel-place',
    actionType: 'lease_signing',
    needsTime: true,
    labels: {
      en: 'Sign a lease or move into a home',
      fa: 'امضای اجاره‌نامه یا اسباب‌کشی',
      ru: 'Подписать аренду или переехать',
      ar: 'توقيع عقد إيجار أو الانتقال إلى منزل',
    },
  },
  {
    id: 'book-flight',
    categoryId: 'travel-place',
    actionType: 'flight_booking',
    needsTime: false,
    labels: {
      en: 'Book a flight or long-distance trip',
      fa: 'رزرو پرواز یا سفر دور',
      ru: 'Забронировать перелёт или дальнюю поездку',
      ar: 'حجز رحلة جوية أو سفر بعيد',
    },
  },
  {
    id: 'change-neighborhood',
    categoryId: 'travel-place',
    actionType: 'neighborhood_change',
    needsTime: false,
    labels: {
      en: 'Move to a new neighborhood or district',
      fa: 'جابجایی به محله یا منطقه جدید',
      ru: 'Переехать в новый район',
      ar: 'الانتقال إلى حي أو منطقة جديدة',
    },
  },
  {
    id: 'vacation-planning',
    categoryId: 'travel-place',
    actionType: 'vacation_planning',
    needsTime: false,
    labels: {
      en: 'Plan a vacation or leisure trip',
      fa: 'برنامه‌ریزی برای تعطیلات یا سفر تفریحی',
      ru: 'Спланировать отпуск или отдых',
      ar: 'تخطيط إجازة أو رحلة ترفيهية',
    },
  },

  // ── Communication & Voice ───────────────────────────────────────────────────
  {
    id: 'social-post',
    categoryId: 'communication',
    actionType: 'social_media_post',
    needsTime: true,
    labels: {
      en: 'Post on social media',
      fa: 'پست در شبکه اجتماعی',
      ru: 'Публикация в соцсетях',
      ar: 'نشر في وسائل التواصل',
    },
  },
  {
    id: 'give-pitch',
    categoryId: 'communication',
    actionType: 'presentation',
    needsTime: true,
    labels: {
      en: 'Give a pitch or presentation',
      fa: 'ارائه یا پرزنتیشن',
      ru: 'Презентация или питч',
      ar: 'تقديم عرض أو بريزنتيشن',
    },
  },
  {
    id: 'creative-launch',
    categoryId: 'communication',
    actionType: 'creative_project',
    needsTime: false,
    labels: {
      en: 'Launch a creative project (book, music, art)',
      fa: 'شروع پروژه خلاقانه (کتاب، موسیقی، هنر)',
      ru: 'Запустить творческий проект',
      ar: 'إطلاق مشروع إبداعي',
    },
  },
  {
    id: 'publish-content',
    categoryId: 'communication',
    actionType: 'content_publish',
    needsTime: true,
    labels: {
      en: 'Publish an article, video, or newsletter',
      fa: 'انتشار مقاله، ویدیو یا خبرنامه',
      ru: 'Опубликовать статью, видео или рассылку',
      ar: 'نشر مقال أو فيديو أو نشرة',
    },
  },
  {
    id: 'public-speaking',
    categoryId: 'communication',
    actionType: 'public_speaking',
    needsTime: true,
    labels: {
      en: 'Give a talk or speak in public',
      fa: 'سخنرانی یا صحبت در جمع',
      ru: 'Выступить с докладом или перед публикой',
      ar: 'إلقاء محاضرة أو التحدث أمام جمهور',
    },
  },
  {
    id: 'negotiate',
    categoryId: 'communication',
    actionType: 'negotiation',
    needsTime: true,
    labels: {
      en: 'Negotiate terms or reach an agreement',
      fa: 'مذاکره روی شرایط یا رسیدن به توافق',
      ru: 'Обсудить условия или договориться',
      ar: 'التفاوض على الشروط أو التوصل لاتفاق',
    },
  },
  {
    id: 'media-interview',
    categoryId: 'communication',
    actionType: 'media_interview',
    needsTime: true,
    labels: {
      en: 'Give a media or podcast interview',
      fa: 'مصاحبه رسانه‌ای یا پادکست',
      ru: 'Дать интервью для СМИ или подкаста',
      ar: 'إجراء مقابلة إعلامية أو بودكاست',
    },
  },
  {
    id: 'difficult-email',
    categoryId: 'communication',
    actionType: 'written_communication',
    needsTime: false,
    labels: {
      en: 'Send a difficult or sensitive message',
      fa: 'ارسال پیام سخت یا حساس',
      ru: 'Отправить сложное или деликатное сообщение',
      ar: 'إرسال رسالة صعبة أو حساسة',
    },
  },

  // ── Decisions & Timing ──────────────────────────────────────────────────────
  {
    id: 'take-risk',
    categoryId: 'decisions-timing',
    actionType: 'risk_taking',
    needsTime: true,
    labels: {
      en: 'Take a calculated risk',
      fa: 'قبول یک ریسک حساب‌شده',
      ru: 'Пойти на просчитанный риск',
      ar: 'الإقدام على مخاطرة محسوبة',
    },
  },
  {
    id: 'fresh-start',
    categoryId: 'decisions-timing',
    actionType: 'fresh_start',
    needsTime: false,
    labels: {
      en: 'Start something completely new',
      fa: 'شروع کاری کاملاً جدید',
      ru: 'Начать что-то совершенно новое',
      ar: 'بدء شيء جديد تمامًا',
    },
  },
  {
    id: 'cut-tie',
    categoryId: 'decisions-timing',
    actionType: 'ending_chapter',
    needsTime: false,
    labels: {
      en: 'Close a chapter / cut something off',
      fa: 'بستن یک فصل / قطع کردن چیزی',
      ru: 'Закрыть главу / прервать что-то',
      ar: 'إغلاق فصل / قطع شيء',
    },
  },
  {
    id: 'big-decision',
    categoryId: 'decisions-timing',
    actionType: 'major_decision',
    needsTime: true,
    labels: {
      en: 'Make a major life decision',
      fa: 'اتخاذ یک تصمیم بزرگ زندگی',
      ru: 'Принять важное решение',
      ar: 'اتخاذ قرار مهم في الحياة',
    },
  },
  {
    id: 'chance-event',
    categoryId: 'decisions-timing',
    actionType: 'chance_event',
    needsTime: true,
    labels: {
      en: 'Buy a lottery ticket / chance opportunity',
      fa: 'خرید بلیط بخت‌آزمایی / فرصت شانسی',
      ru: 'Лотерея / случайная возможность',
      ar: 'شراء تذكرة يانصيب / فرصة',
    },
  },
  {
    id: 'wait-or-act',
    categoryId: 'decisions-timing',
    actionType: 'timing_decision',
    needsTime: false,
    labels: {
      en: 'Wait or act now on an important matter',
      fa: 'صبر کنم یا همین حالا اقدام کنم؟',
      ru: 'Подождать или действовать сейчас?',
      ar: 'أنتظر أم أتحرك الآن في أمر مهم؟',
    },
  },
  {
    id: 'change-career-path',
    categoryId: 'decisions-timing',
    actionType: 'career_change',
    needsTime: false,
    labels: {
      en: 'Change career direction or industry',
      fa: 'تغییر مسیر شغلی یا صنعت',
      ru: 'Сменить карьерное направление или отрасль',
      ar: 'تغيير المسار المهني أو المجال',
    },
  },
  {
    id: 'legal-decision',
    categoryId: 'decisions-timing',
    actionType: 'legal_decision',
    needsTime: true,
    labels: {
      en: 'Make a legal or formal decision',
      fa: 'اتخاذ تصمیم حقوقی یا رسمی',
      ru: 'Принять юридическое или формальное решение',
      ar: 'اتخاذ قرار قانوني أو رسمي',
    },
  },

  // ── Energy & Focus ──────────────────────────────────────────────────────────
  {
    id: 'todays-focus',
    categoryId: 'energy-focus',
    actionType: 'daily_focus',
    needsTime: false,
    labels: {
      en: 'What deserves my attention most today?',
      fa: 'امروز چه چیزی بیش از همه شایسته توجه من است؟',
      ru: 'Что заслуживает моего внимания сегодня?',
      ar: 'ما الذي يستحق اهتمامي اليوم؟',
    },
  },
  {
    id: 'use-energy-wisely',
    categoryId: 'energy-focus',
    actionType: 'energy_management',
    needsTime: false,
    labels: {
      en: 'How can I use my energy wisely today?',
      fa: 'چطور می‌توانم امروز انرژی‌ام را هوشمندانه مدیریت کنم؟',
      ru: 'Как разумно распорядиться энергией сегодня?',
      ar: 'كيف أستخدم طاقتي بحكمة اليوم؟',
    },
  },
  {
    id: 'notice-opportunity',
    categoryId: 'energy-focus',
    actionType: 'opportunity_awareness',
    needsTime: false,
    labels: {
      en: 'What opportunity should I pay attention to right now?',
      fa: 'به کدام فرصت باید همین حالا توجه کنم؟',
      ru: 'На какую возможность обратить внимание?',
      ar: 'أي فرصة يجب أن أنتبه لها الآن؟',
    },
  },
  {
    id: 'deep-work-day',
    categoryId: 'energy-focus',
    actionType: 'deep_work',
    needsTime: false,
    labels: {
      en: 'Schedule a deep work or focus day',
      fa: 'برنامه‌ریزی برای روز کار عمیق یا تمرکز',
      ru: 'Запланировать день глубокой работы',
      ar: 'جدولة يوم عمل عميق أو تركيز',
    },
  },
  {
    id: 'rest-recover',
    categoryId: 'energy-focus',
    actionType: 'rest_recovery',
    needsTime: false,
    labels: {
      en: 'Take a rest day or recover energy',
      fa: 'روز استراحت یا بازیابی انرژی',
      ru: 'Взять день отдыха или восстановить силы',
      ar: 'أخذ يوم راحة أو استعادة الطاقة',
    },
  },
  {
    id: 'avoid-burnout',
    categoryId: 'energy-focus',
    actionType: 'burnout_prevention',
    needsTime: false,
    labels: {
      en: 'Protect myself from burnout this week',
      fa: 'محافظت از خودم در برابر فرسودگی این هفته',
      ru: 'Защитить себя от выгорания на этой неделе',
      ar: 'حماية نفسي من الإرهاق هذا الأسبوع',
    },
  },
  {
    id: 'set-priorities',
    categoryId: 'energy-focus',
    actionType: 'priority_setting',
    needsTime: false,
    labels: {
      en: 'Set priorities for the week ahead',
      fa: 'تعیین اولویت‌ها برای هفته پیش رو',
      ru: 'Определить приоритеты на предстоящую неделю',
      ar: 'تحديد الأولويات للأسبوع القادم',
    },
  },
  {
    id: 'morning-routine',
    categoryId: 'energy-focus',
    actionType: 'morning_routine',
    needsTime: true,
    labels: {
      en: 'Start or reset a morning routine',
      fa: 'شروع یا بازنشانی روتین صبحگاهی',
      ru: 'Начать или обновить утренний ритуал',
      ar: 'بدء أو إعادة ضبط روتين الصباح',
    },
  },

  // ── Home & Family ───────────────────────────────────────────────────────────
  {
    id: 'move-home',
    categoryId: 'home-family',
    actionType: 'home_move',
    needsTime: false,
    labels: {
      en: 'Move to a new home',
      fa: 'اسباب‌کشی به خانه جدید',
      ru: 'Переехать в новый дом',
      ar: 'الانتقال إلى منزل جديد',
    },
  },
  {
    id: 'family-celebration',
    categoryId: 'home-family',
    actionType: 'family_celebration',
    needsTime: true,
    labels: {
      en: 'Plan a family celebration or event',
      fa: 'برنامه‌ریزی برای جشن یا رویداد خانوادگی',
      ru: 'Запланировать семейный праздник или событие',
      ar: 'تخطيط احتفال أو مناسبة عائلية',
    },
  },
  {
    id: 'home-renovation',
    categoryId: 'home-family',
    actionType: 'home_renovation',
    needsTime: false,
    labels: {
      en: 'Start a home renovation or repair',
      fa: 'شروع بازسازی یا تعمیر خانه',
      ru: 'Начать ремонт или обновление дома',
      ar: 'بدء تجديد أو إصلاح المنزل',
    },
  },
  {
    id: 'have-child',
    categoryId: 'home-family',
    actionType: 'family_planning',
    needsTime: false,
    labels: {
      en: 'Plan for having a child or expanding the family',
      fa: 'برنامه‌ریزی برای فرزند یا گسترش خانواده',
      ru: 'Планировать рождение ребёнка или расширение семьи',
      ar: 'التخطيط لإنجاب طفل أو توسيع العائلة',
    },
  },
  {
    id: 'elder-care',
    categoryId: 'home-family',
    actionType: 'elder_care',
    needsTime: false,
    labels: {
      en: 'Arrange care for an elderly family member',
      fa: 'ترتیب مراقبت از عضو مسن خانواده',
      ru: 'Организовать уход за пожилым родственником',
      ar: 'ترتيب رعاية لأحد أفراد العائلة كبار السن',
    },
  },
  {
    id: 'pet-adoption',
    categoryId: 'home-family',
    actionType: 'pet_adoption',
    needsTime: false,
    labels: {
      en: 'Adopt a pet or welcome one into the home',
      fa: 'فرزندخواندگی حیوان یا پذیرش در خانه',
      ru: 'Завести питомца или принять его в дом',
      ar: 'تبني حيوان أليف أو استقباله في المنزل',
    },
  },
  {
    id: 'household-purchase',
    categoryId: 'home-family',
    actionType: 'household_purchase',
    needsTime: false,
    labels: {
      en: 'Make a major household purchase',
      fa: 'خرید بزرگ برای خانه',
      ru: 'Сделать крупную покупку для дома',
      ar: 'إجراء شراء كبير للمنزل',
    },
  },
  {
    id: 'family-meeting',
    categoryId: 'home-family',
    actionType: 'family_meeting',
    needsTime: true,
    labels: {
      en: 'Hold an important family meeting',
      fa: 'برگزاری جلسه مهم خانوادگی',
      ru: 'Провести важное семейное собрание',
      ar: 'عقد اجتماع عائلي مهم',
    },
  },

  // ── Growth & Learning ───────────────────────────────────────────────────────
  {
    id: 'start-course',
    categoryId: 'growth-learning',
    actionType: 'course_start',
    needsTime: false,
    labels: {
      en: 'Start a course or training program',
      fa: 'شروع دوره یا برنامه آموزشی',
      ru: 'Начать курс или программу обучения',
      ar: 'بدء دورة أو برنامج تدريبي',
    },
  },
  {
    id: 'learn-skill',
    categoryId: 'growth-learning',
    actionType: 'skill_learning',
    needsTime: false,
    labels: {
      en: 'Learn a new skill or craft',
      fa: 'یادگیری مهارت یا هنر جدید',
      ru: 'Освоить новый навык или ремесло',
      ar: 'تعلم مهارة أو حرفة جديدة',
    },
  },
  {
    id: 'start-habit',
    categoryId: 'growth-learning',
    actionType: 'habit_formation',
    needsTime: false,
    labels: {
      en: 'Build a new daily habit',
      fa: 'ساخت عادت روزانه جدید',
      ru: 'Сформировать новую ежедневную привычку',
      ar: 'بناء عادة يومية جديدة',
    },
  },
  {
    id: 'read-book',
    categoryId: 'growth-learning',
    actionType: 'reading_commitment',
    needsTime: false,
    labels: {
      en: 'Commit to reading or studying a book',
      fa: 'تعهد به خواندن یا مطالعه یک کتاب',
      ru: 'Взять обязательство прочитать или изучить книгу',
      ar: 'الالتزام بقراءة أو دراسة كتاب',
    },
  },
  {
    id: 'mentorship',
    categoryId: 'growth-learning',
    actionType: 'mentorship',
    needsTime: true,
    labels: {
      en: 'Seek a mentor or begin mentoring someone',
      fa: 'جستجوی منتور یا شروع راهنمایی کسی',
      ru: 'Найти наставника или начать наставничество',
      ar: 'البحث عن مرشد أو بدء إرشاد شخص',
    },
  },
  {
    id: 'certification-exam',
    categoryId: 'growth-learning',
    actionType: 'certification_exam',
    needsTime: true,
    labels: {
      en: 'Take a certification or qualification exam',
      fa: 'شرکت در آزمون گواهینامه یا مدرک',
      ru: 'Сдать экзамен на сертификацию или квалификацию',
      ar: 'خوض امتحان شهادة أو مؤهل',
    },
  },
  {
    id: 'creative-practice',
    categoryId: 'growth-learning',
    actionType: 'creative_practice',
    needsTime: false,
    labels: {
      en: 'Start a regular creative practice',
      fa: 'شروع تمرین خلاقانه منظم',
      ru: 'Начать регулярную творческую практику',
      ar: 'بدء ممارسة إبداعية منتظمة',
    },
  },
  {
    id: 'journaling-reflection',
    categoryId: 'growth-learning',
    actionType: 'journaling',
    needsTime: false,
    labels: {
      en: 'Begin journaling or self-reflection',
      fa: 'شروع نوشتن روزانه یا خودشناسی',
      ru: 'Начать вести дневник или саморефлексию',
      ar: 'بدء كتابة اليوميات أو التأمل الذاتي',
    },
  },
];
