/** Known Style Timing palette names → swatch hex. Unknown names stay text-only. */

const SWATCHES: Record<string, string> = {
  'Flame red': '#C62828',
  'Warm coral': '#E07050',
  'Rose pink': '#D67A9C',
  'Soft sage green': '#7A9A7A',
  'Butter yellow': '#E6C35C',
  'Light mint': '#8FCFB8',
  'Pearl silver': '#C5C8CE',
  'Soft white': '#F4F1EA',
  Gold: '#C9A227',
  'Sunset orange': '#E07A3A',
  'Stone beige': '#C4B49A',
  Navy: '#1B3A5F',
  'Blush rose': '#D9A0B0',
  'Powder blue': '#8FB4D9',
  'Deep burgundy': '#6B1E2F',
  Black: '#1A1A1A',
  'Royal purple': '#5B3A8C',
  'Cobalt blue': '#1E4DB7',
  Charcoal: '#3A3A3A',
  'Dark chocolate': '#4A2E1F',
  'Electric blue': '#2B6BE6',
  Turquoise: '#2AA8A0',
  'Seafoam green': '#7EBEA8',
  Lavender: '#A78BBE',
  'قرمز شعله‌ای': '#C62828',
  'مرجانی گرم': '#E07050',
  'صورتی گل‌سرخی': '#D67A9C',
  'سبز مریم‌گلی': '#7A9A7A',
  'زرد کره‌ای': '#E6C35C',
  'نعنایی روشن': '#8FCFB8',
  'نقره‌ای مرواریدی': '#C5C8CE',
  'سفید نرم': '#F4F1EA',
  طلایی: '#C9A227',
  'نارنجی غروب': '#E07A3A',
  'بژ سنگی': '#C4B49A',
  سرمه‌ای: '#1B3A5F',
  'رز براق': '#D9A0B0',
  'آبی پودری': '#8FB4D9',
  'شرابی تیره': '#6B1E2F',
  مشکی: '#1A1A1A',
  'بنفش سلطنتی': '#5B3A8C',
  'آبی کبالت': '#1E4DB7',
  ذغالی: '#3A3A3A',
  'شکلاتی تیره': '#4A2E1F',
  'آبی الکتریکی': '#2B6BE6',
  فیروزه‌ای: '#2AA8A0',
  'سبز دریایی': '#7EBEA8',
  اسطوخودوس: '#A78BBE',
  'Алый красный': '#C62828',
  'Тёплый коралл': '#E07050',
  Розовый: '#D67A9C',
  'Мягкий шалфей': '#7A9A7A',
  'Масляно-жёлтый': '#E6C35C',
  'Светлая мята': '#8FCFB8',
  'Жемчужное серебро': '#C5C8CE',
  'Мягкий белый': '#F4F1EA',
  Золото: '#C9A227',
  'Закатный оранжевый': '#E07A3A',
  'Каменный беж': '#C4B49A',
  'Тёмно-синий': '#1B3A5F',
  'Нежная роза': '#D9A0B0',
  'Пудрово-голубой': '#8FB4D9',
  'Глубокий бордо': '#6B1E2F',
  Чёрный: '#1A1A1A',
  'Королевский фиолетовый': '#5B3A8C',
  Кобальт: '#1E4DB7',
  Угольный: '#3A3A3A',
  'Тёмный шоколад': '#4A2E1F',
  'Электрический синий': '#2B6BE6',
  Бирюза: '#2AA8A0',
  'Морская пена': '#7EBEA8',
  Лаванда: '#A78BBE',
  'أحمر قرمزي': '#C62828',
  'مرجاني دافئ': '#E07050',
  'وردي وردي': '#D67A9C',
  'أخضر مريمية': '#7A9A7A',
  'أصفر زبدي': '#E6C35C',
  'نعناع فاتح': '#8FCFB8',
  'فضي لؤلؤي': '#C5C8CE',
  'أبيض ناعم': '#F4F1EA',
  ذهبي: '#C9A227',
  'برتقالي غروب': '#E07A3A',
  'بيج حجري': '#C4B49A',
  كحلي: '#1B3A5F',
  'وردي خجول': '#D9A0B0',
  'أزرق بودري': '#8FB4D9',
  'خمري عميق': '#6B1E2F',
  أسود: '#1A1A1A',
  'بنفسجي ملكي': '#5B3A8C',
  'أزرق كوبالت': '#1E4DB7',
  فحمي: '#3A3A3A',
  'شوكولا داكن': '#4A2E1F',
  'أزرق كهربائي': '#2B6BE6',
  فيروزي: '#2AA8A0',
  'أخضر بحري': '#7EBEA8',
  لافندر: '#A78BBE',
};

export function swatchHexForPaletteName(name: string): string | null {
  const key = name.trim();
  return key ? SWATCHES[key] ?? null : null;
}

export function splitPaletteNames(value: string): string[] {
  return value
    .split(/\s*·\s*/)
    .map((part) => part.trim())
    .filter(Boolean);
}
