"""Conversation API Contract v1.0 — public HTTP route (ADR-0007 + Amendment A1).

ADR-0007 Amendment A1 authorises exactly:

    POST /api/v1/conversation/execute

Router mounting contract:

* Router prefix in ``main.py``: ``/api/v1/conversation``
* Route path in this module: ``/execute``
* Final public route: ``POST /api/v1/conversation/execute``

``/api/v1/conversation/chat`` is not authorised and MUST remain unmounted.

Contract-surface acceptance lives in:
``services.conversation_request_acceptance``
``services.conversation_boundary``
``schemas.conversation``

Exception handling for versioned Decision routes remains owned by
``routes.decision.register_decision_exception_handlers`` without override.
"""

from __future__ import annotations

from typing import Any

from fastapi import APIRouter, Request
from fastapi.responses import JSONResponse

from schemas.conversation import (
    ConversationApiErrorBody,
    ConversationApiErrorResponse,
    ConversationResponse,
)
from services.conversation_boundary import execute_conversation_boundary
from services.conversation_request_acceptance import (
    ConversationAcceptanceError,
    accept_conversation_request_body,
    generate_conversation_request_id,
)

router = APIRouter()

CONVERSATION_EXECUTE_PATH = "/api/v1/conversation/execute"


def _error_response(
    *,
    status_code: int,
    code: str,
    message: str,
    request_id: str,
) -> JSONResponse:
    body = ConversationApiErrorResponse(
        error=ConversationApiErrorBody(
            code=code,
            message=message,
            requestId=request_id,
        )
    )
    return JSONResponse(status_code=status_code, content=body.model_dump(by_alias=True))


def register_conversation_openapi_filter(app: Any) -> None:
    """Remove FastAPI's autogenerated 422 from the Conversation execute operation only."""
    original_openapi = app.openapi

    def filtered_openapi() -> dict[str, Any]:
        schema = original_openapi()
        path_item = schema.get("paths", {}).get(CONVERSATION_EXECUTE_PATH, {})
        post = path_item.get("post", {})
        post.get("responses", {}).pop("422", None)
        return schema

    app.openapi = filtered_openapi


@router.post(
    "/execute",
    response_model=ConversationResponse,
    responses={
        400: {
            "model": ConversationApiErrorResponse,
            "description": "Request contract validation failure",
        },
        500: {
            "model": ConversationApiErrorResponse,
            "description": "Internal execution failure",
        },
    },
)
async def execute_conversation(
    request: Request,
) -> ConversationResponse | JSONResponse:
    """Accept raw body bytes, then execute the Conversation contract boundary."""
    request_id: str | None = None
    try:
        raw_body = await request.body()
        accepted = accept_conversation_request_body(raw_body)
        if isinstance(accepted, ConversationAcceptanceError):
            return JSONResponse(
                status_code=accepted.status_code,
                content=accepted.to_envelope_dict(),
            )

        request_id = accepted.request_id
        return execute_conversation_boundary(
            accepted.request,
            request_id=accepted.request_id,
        )
    except Exception:
        return _error_response(
            status_code=500,
            code="INTERNAL_ERROR",
            message="Internal conversation execution failure",
            request_id=request_id or generate_conversation_request_id(),
        )
