/** Locale-aware prose catalog for Personal Intelligence generators. */

import type { AppLang } from '@/lib/app-settings';

export const INTELLIGENCE_UNAVAILABLE: Record<AppLang, string> = {
  en: 'Personal insight unavailable in this language.',
  fa: 'این بینش به این زبان در دسترس نیست.',
  ru: 'Этот инсайт недоступен на этом языке.',
  ar: 'هذه الرؤية غير متاحة بهذه اللغة.',
};

const PROSE: Record<AppLang, Record<string, string>> = {
  en: {
    'blind.acts-too-quickly.description': 'Speed helps — pause once when the downside is hard to reverse.',
    'blind.acts-too-quickly.label': 'Acts too quickly',
    'blind.acts-too-quickly.mitigation': 'Set a time-boxed decision window and a reversible default action.',
    'blind.acts-too-quickly.trigger': 'High ambiguity with a soft deadline',
    'blind.avoids-conflict.description': 'Harmony preference can postpone necessary hard conversations.',
    'blind.avoids-conflict.label': 'Avoids conflict',
    'blind.avoids-conflict.mitigation': 'Name one required conversation and schedule it before locking the move.',
    'blind.avoids-conflict.trigger': 'Interpersonal disagreement around the decision',
    'blind.context-switching.description': 'Parallel threads dilute judgment; batch decisions by domain.',
    'blind.context-switching.label': 'Context switching',
    'blind.context-switching.mitigation': 'Batch by domain and close one decision before opening another.',
    'blind.context-switching.trigger': 'Multiple open decisions in one day',
    'blind.deferred-follow-through.description': 'Insight arrives early; close the loop with a dated next action.',
    'blind.deferred-follow-through.label': 'Deferred follow-through',
    'blind.deferred-follow-through.mitigation': 'Attach a calendar date and owner to the next concrete step.',
    'blind.deferred-follow-through.trigger': 'Post-decision relief',
    'blind.goes-solo-early.description': 'Independent drive can skip a stakeholder who reduces risk.',
    'blind.goes-solo-early.label': 'Goes solo too early',
    'blind.goes-solo-early.mitigation': 'Name one required conversation and schedule it before locking the move.',
    'blind.goes-solo-early.trigger': 'Interpersonal disagreement around the decision',
    'blind.overthinks.description': 'Extra analysis can delay reversible moves that would teach faster.',
    'blind.overthinks.label': 'Overthinks',
    'blind.overthinks.mitigation': 'Set a time-boxed decision window and a reversible default action.',
    'blind.overthinks.trigger': 'High ambiguity with a soft deadline',
    'blind.perfectionism.description': 'Quality standards rise under pressure; define “good enough” checkpoints.',
    'blind.perfectionism.label': 'Perfectionism',
    'blind.perfectionism.mitigation': 'Write a minimum viable success bar before refining further.',
    'blind.perfectionism.trigger': 'Public or high-visibility outcomes',
    'blind.risk-avoidance.description': 'Caution protects you — also schedule one controlled experiment.',
    'blind.risk-avoidance.label': 'Risk avoidance',
    'blind.risk-avoidance.mitigation': 'Separate reversible pilots from irreversible commitments on a written list.',
    'blind.risk-avoidance.trigger': 'Downside-heavy options',
    'blind.surge-decisions.description': 'Energy spikes can compress deliberation; sleep on irreversible calls.',
    'blind.surge-decisions.label': 'Emotional surge decisions',
    'blind.surge-decisions.mitigation': 'Separate reversible pilots from irreversible commitments on a written list.',
    'blind.surge-decisions.trigger': 'Time pressure + strong emotion',
    'communication.approach': 'State the decision, the criteria, and the ask in three sentences before debating options.',
    'communication.conflict.align': 'Seeks alignment; may delay confrontation until stakes force it',
    'communication.conflict.direct': 'Addresses issues head-on; may under-index on emotional pacing',
    'communication.env.flexible': 'Flexible forums with explicit goals',
    'communication.env.prepared': 'Prepared 1:1 or focused small groups',
    'communication.listen.action': 'Listens for intent and momentum; summarizes toward action',
    'communication.listen.analytical': 'Listens for structure, inconsistencies, and decision criteria',
    'communication.persuade.ask': 'Clear ask and ownership first',
    'communication.persuade.evidence': 'Evidence and criteria first',
    'communication.persuade.narrative': 'Narrative and options first',
    'communication.primary.direct': 'Direct and outcome-oriented',
    'communication.primary.relational': 'Relational and context-rich',
    'communication.risk.brevity': 'Brevity can skip emotional context others need',
    'communication.risk.criteria': 'Unstated decision criteria create false agreement',
    'communication.risk.harmony': 'Harmony preference can bury disagreement',
    'conf.blindSpots': 'Blind-spot labels are decision-risk patterns, not diagnoses.',
    'conf.communication': 'Communication style is a decision-support model for People and Julia.',
    'conf.comparative': 'Comparative signals only — not deterministic prediction.',
    'conf.complete': 'Profile built from complete birth timing inputs.',
    'conf.decisionStyle': 'Decision style confidence tracks completeness of birth timing inputs.',
    'conf.decisionStyle.limit': 'Style labels are controlled enums, not free-form personality claims.',
    'conf.energy': 'Energy bands are relative, not hour-level forecasts.',
    'conf.energy.limit': 'Do not treat bands as guaranteed peak performance times.',
    'conf.environment': 'Environment recommendations support judgment quality, not workplace mandates.',
    'conf.growth': 'Growth areas are decision-practice recommendations, not self-help promises.',
    'conf.leadership': 'Leadership here means influence and responsibility, not job title.',
    'conf.learning': 'Learning preferences support decision skill growth, not academic labels.',
    'conf.opportunity': 'Opportunity scores are relative strengths across zones, not forecasts.',
    'conf.opportunity.limit': 'Do not interpret as certainty of outcomes.',
    'conf.partial': 'Partial profile — complete onboarding to raise confidence.',
    'conf.pressure': 'Pressure patterns are timing-derived tendencies, not clinical assessments.',
    'conf.strengths': 'Strength signals are comparative timing-derived patterns.',
    'conf.work': 'Work style describes decision-supporting rhythm, not productivity guarantees.',
    'decision-style.explanation': 'Primary mode is {primary}, with secondary leanings toward {secondary}. Risk posture is {risk}; pace tends {speed}. Derived from birth timing anchors and profile metadata — comparative, not predictive.',
    'decision-style.secondary.fallback': 'adaptive adjustment',
    'energy.explanation.adjusted': ', softly adjusted by today’s timing score.',
    'energy.explanation.base': 'Relative energy bands from birth timing anchors',
    'energy.explanation.full.adjusted': 'Relative energy bands from birth timing anchors, softly adjusted by today’s timing score.',
    'energy.explanation.full.noLive': 'Relative energy bands from birth timing anchors. Live hourly precision requires the timing engine separately.',
    'energy.explanation.noLive': '. Live hourly precision requires the timing engine separately.',
    'energy.recovery.afternoon': 'Late afternoon reset before evening commitments',
    'energy.recovery.midday': 'Mid-afternoon pause between decision blocks',
    'energy.recovery.morning': 'Late morning buffer after early obligations',
    'env.collab.high': 'High for major calls',
    'env.collab.selective': 'Selective consultation',
    'env.distraction.high': 'High',
    'env.distraction.moderate': 'Moderate',
    'env.info.criteria': 'Criteria and evidence before commit',
    'env.info.options': 'Clear options and a reversible next step',
    'env.pressure.high': 'Moderate–high',
    'env.pressure.low': 'Low–moderate',
    'env.setting.collaborative': 'Collaborative',
    'env.setting.flexible': 'Flexible',
    'env.setting.quiet': 'Quiet',
    'env.setting.remote': 'Remote / controlled',
    'env.setting.stable': 'Stable workspace',
    'env.setting.travel': 'Travel-friendly',
    'env.setup': 'Quiet or prepared small-group setting, written criteria, one reversible pilot, and a hard review time.',
    'error.loadFailed': 'Unable to load personal intelligence profile.',
    'evidence.countOnly': 'Count only — raw history not embedded in profile.',
    'evidence.derived': 'Derived from available profile timing anchors only.',
    'evidence.partial': 'Partial profile — missing inputs reduced confidence.',
    'growth.blind-spot.area': 'Primary blind-spot watch',
    'growth.blind-spot.practice.unnamed': 'Name your top risk in one sentence before deciding.',
    'growth.blind-spot.reason': 'Pattern “{label}” appears under load.',
    'growth.blind-spot.reason.unnamed': 'Unnamed risk slows recovery after decisions.',
    'growth.blind-spot.review': 'Biweekly',
    'growth.blind-spot.success': 'One explicit checkpoint attached to the next high-stakes decision.',
    'growth.conflict.area': 'Direct conflict practice',
    'growth.conflict.practice': 'Practice one prepared direct conversation per month.',
    'growth.conflict.reason': 'Alignment preference can delay necessary friction.',
    'growth.conflict.review': 'Monthly',
    'growth.conflict.success': 'Decision notes include at least one contrary input.',
    'growth.dissent.area': 'Dissenting input',
    'growth.dissent.practice': 'Invite one dissenting view before locking major moves.',
    'growth.dissent.reason': 'Independent drive can miss risk-reducing stakeholders.',
    'growth.protected.area': 'Protected decision blocks',
    'growth.protected.practice': 'Protect one deep-work decision block on high-stakes days.',
    'growth.protected.reason': 'Judgment quality drops without uninterrupted focus.',
    'growth.protected.review': 'Weekly',
    'growth.protected.success': 'Calendar shows a labeled decision block before major calls.',
    'growth.reversible.area': 'Reversible-first commitments',
    'growth.reversible.practice': 'Define a 48-hour reversible experiment before any irreversible commitment.',
    'growth.reversible.reason': 'Irreversible moves without pilots raise downside.',
    'growth.reversible.review': 'Monthly',
    'growth.reversible.success': 'Every major decision log includes a pilot step and date.',
    'growth.review.area': 'Decision review habit',
    'growth.review.practice': 'Review saved decisions monthly: what changed vs. what you recommended.',
    'growth.review.reason': 'Without review, recommendations do not compound into skill.',
    'growth.review.review': 'Monthly',
    'growth.review.success': 'Vault or Pathfinder history shows a dated review note.',
    'horizon.balanced': 'Balanced',
    'horizon.long-term': 'Long-term',
    'horizon.near-term': 'Near-term',
    'independence.collaborative': 'Collaborative',
    'independence.independent': 'Independent',
    'independence.selective': 'Selective',
    'leadership.development': 'Practice stating criteria and next owner in every decision brief you lead.',
    'leadership.environment': 'Clear ownership, explicit success signals, and room for reversible experiments.',
    'leadership.primary.analyst': 'Analyst',
    'leadership.primary.builder': 'Builder',
    'leadership.primary.mentor': 'Mentor',
    'leadership.primary.vision': 'Vision driven',
    'leadership.risk.analysis': 'Analysis delay under urgency',
    'leadership.risk.conflict': 'Conflict avoidance',
    'leadership.risk.execution': 'Under-specified execution',
    'leadership.risk.optimize': 'Over-optimizing the build before alignment',
    'leadership.secondary.adaptive': 'Adaptive',
    'leadership.secondary.operational': 'Operational',
    'leadership.strength.align': 'Aligns shared outcomes',
    'leadership.strength.contribution': 'Invites contribution',
    'leadership.strength.destination': 'Sets destination',
    'leadership.strength.evidence': 'Raises decision quality with evidence',
    'leadership.strength.people': 'Develops people',
    'leadership.strength.ships': 'Ships progress',
    'leadership.strength.systems': 'Refines systems in motion',
    'leadership.strength.tradeoffs': 'Clarifies trade-offs',
    'learning.barrier.frameworks': 'Collecting frameworks without a live application',
    'learning.barrier.reflection': 'Skipping reflection after experiments',
    'learning.method.analytical': 'Analytical',
    'learning.method.discussion': 'Discussion',
    'learning.method.experimentation': 'Experimentation',
    'learning.method.practical': 'Practical',
    'learning.method.reading': 'Reading',
    'learning.method.visual': 'Visual mapping',
    'learning.practice': 'Apply within 48 hours of learning',
    'learning.processing.models': 'Models that explain real cases',
    'learning.processing.real': 'Small real versions first',
    'learning.recommended': '{primary} first, then {secondary} to stress-test understanding.',
    'learning.retention': 'Teach-back or written decision note after practice',
    'legacy.blind.why': '{description} Mitigation: {mitigation}',
    'legacy.fast.label': 'Fast',
    'legacy.fast.why': 'Decision speed leans fast when inputs are clear.',
    'legacy.patient.label': 'Patient',
    'legacy.patient.why': 'Risk orientation favors deliberate pacing.',
    'legacy.riskBalanced.label': 'Risk Balanced',
    'legacy.riskBalanced.why': 'Risk orientation: {risk}.',
    'limit.comparative': 'Comparative decision-support only.',
    'limit.noLiveTiming': 'Live timing context not supplied at build time.',
    'pressure.protocol': 'Name the irreversible part, shrink the next step to a reversible action, and decide inside a stronger energy band with a dated checkpoint.',
    'pressure.recovery.default': 'A short walk-away, then one concrete next step, restores pacing.',
    'pressure.recovery.morning': 'Early quiet resets plus a written priority list restore judgment quality.',
    'pressure.response.action': 'Accelerates toward action; ambiguity can feel like lost momentum.',
    'pressure.response.analytical': 'Narrows focus and seeks more data; urgency can feel like incomplete information.',
    'pressure.risk.action': 'Compressing deliberation increases irreversible error risk.',
    'pressure.risk.analytical': 'Over-collecting inputs delays reversible learning.',
    'pressure.trigger.deadlines': 'Hard deadlines with incomplete information',
    'pressure.trigger.disagreement': 'Interpersonal disagreement',
    'pressure.trigger.irreversible': 'Irreversible downside without a pilot path',
    'pressure.trigger.silence': 'Stakeholder silence when ownership is unclear',
    'risk.balanced': 'Balanced',
    'risk.bold': 'Bold',
    'risk.cautious': 'Cautious',
    'speed.deliberate': 'Deliberate',
    'speed.fast': 'Fast',
    'speed.measured': 'Measured',
    'strength.communication.application': 'Surface the decision criteria in a short brief before seeking input.',
    'strength.communication.description': 'Clarity improves when ideas are spoken and tested with others.',
    'strength.communication.label': 'Communication',
    'strength.creativity.application': 'Force one non-obvious third option before binary choose/leave.',
    'strength.creativity.description': 'Fresh options surface when constraints are explicit.',
    'strength.creativity.label': 'Creativity',
    'strength.decision-sequencing.application': 'Require a dated reversible pilot before any hard-to-reverse commitment.',
    'strength.decision-sequencing.description': 'Performs best when irreversible steps follow reversible pilots.',
    'strength.decision-sequencing.label': 'Decision sequencing',
    'strength.execution-focus.application': 'Protect one uninterrupted block for the irreversible step.',
    'strength.execution-focus.description': 'Sustained focus windows convert plans into finished work.',
    'strength.execution-focus.label': 'Execution focus',
    'strength.leadership.application': 'State the decision owner and success signal before opening debate.',
    'strength.leadership.description': 'Direction-setting is a natural mode under clear goals.',
    'strength.leadership.label': 'Leadership',
    'strength.learning-speed.application': 'Run a small real version of the option to learn faster than theorizing.',
    'strength.learning-speed.description': 'Absorbs new frameworks quickly when stakes are real.',
    'strength.learning-speed.label': 'Learning speed',
    'strength.long-term-planning.application': 'Use when ranking options by 90-day impact before committing capital or reputation.',
    'strength.long-term-planning.description': 'Frames choices around multi-step outcomes rather than single moves.',
    'strength.long-term-planning.label': 'Long-term planning',
    'strength.negotiation.application': 'List each party\'s must-haves before bargaining on a decision.',
    'strength.negotiation.description': 'Trade-offs become clearer when interests are mapped.',
    'strength.negotiation.label': 'Negotiation',
    'strength.pattern-recognition.application': 'Map two prior analogous decisions before choosing.',
    'strength.pattern-recognition.description': 'Connects signals across contexts before acting.',
    'strength.pattern-recognition.label': 'Pattern recognition',
    'strength.systems-thinking.application': 'Sketch dependency risks before optimizing a single lever.',
    'strength.systems-thinking.description': 'Sees how parts interact before optimizing one piece.',
    'strength.systems-thinking.label': 'Systems thinking',
    'style.adaptive': 'Adaptive',
    'style.analytical': 'Analytical',
    'style.cautious': 'Cautious',
    'style.collaborative': 'Collaborative',
    'style.execution-focused': 'Execution-focused',
    'style.exploratory': 'Exploratory',
    'style.intuitive': 'Intuitive',
    'style.strategic': 'Strategic',
    'style.decisive': 'Decisive',
    'style.risk-aware': 'Risk-aware',
    'summary.body': 'You decide in a {styles} mode, with notable strengths in {strengthLabels}. Leadership tends toward {leadership}, and work rhythm favors {work}. Use reversible pilots before irreversible commitments, and schedule high-stakes calls inside stronger energy bands. These are comparative decision-support signals, not predictions.',
    'work.change.high': 'High — seeks useful novelty',
    'work.change.measured': 'Measured — prefers sequenced change',
    'work.collab.owner': 'Owner-driven',
    'work.collab.team': 'Team-oriented',
    'work.env.deep': 'Low-interruption blocks for high-stakes decisions',
    'work.env.flexible': 'Flexible space with clean decision inputs',
    'work.focus.deep': 'Deep work',
    'work.focus.flexible': 'Flexible switching',
    'work.rhythm.frontload': 'Front-load critical work',
    'work.rhythm.lateday': 'Late-day refinement',
    'work.rhythm.midday': 'Midday execution peaks',
    'work.risk.interruptions': 'Interruptions collapse judgment quality',
    'work.risk.irreversible': 'Starting irreversible work before a reversible pilot',
    'work.risk.switching': 'Context switching without batching',
    'work.structure.adaptive': 'Adaptive structure',
    'work.structure.plans': 'Structured plans',
    'zone.business.label': 'Business',
    'zone.business.bestUse': 'Pilot offers before full commitment.',
    'zone.business.caution': 'Avoid all-or-nothing launches on low readiness days.',
    'zone.business.rationale': 'Profile pattern supports option generation and staged launches.',
    'zone.career.label': 'Career',
    'zone.career.bestUse': 'Prioritize one career lever with a weekly review.',
    'zone.career.caution': 'Do not treat the score as a promotion forecast.',
    'zone.career.rationale': 'Timing anchors favor structured progress against clear role goals.',
    'zone.creativity.label': 'Creativity',
    'zone.creativity.bestUse': 'Force a third option before binary choices.',
    'zone.creativity.caution': 'Novelty without checkpoints increases execution risk.',
    'zone.creativity.rationale': 'Creative banding supports alternative framing under constraints.',
    'zone.leadership.label': 'Leadership',
    'zone.leadership.bestUse': 'Lead decisions by stating criteria and next owner.',
    'zone.leadership.caution': 'Leadership here means influence, not job title.',
    'zone.leadership.rationale': 'Influence patterns favor clarifying ownership and outcomes.',
    'zone.learning.label': 'Learning',
    'zone.learning.bestUse': 'Pair study with a small applied experiment.',
    'zone.learning.caution': 'Completion still depends on practice design.',
    'zone.learning.rationale': 'Learning speed / pattern signals support skill acquisition.',
    'zone.money.label': 'Money',
    'zone.money.bestUse': 'Set downside limits before allocating.',
    'zone.money.caution': 'Score is comparative — not market advice.',
    'zone.money.rationale': 'Analytical banding supports deliberate capital decisions.',
    'zone.networking.label': 'Networking',
    'zone.networking.bestUse': 'Ask for one dissenting view before major locks.',
    'zone.networking.caution': 'Volume of contacts ≠ decision quality.',
    'zone.networking.rationale': 'Collaborative bias improves signal from trusted peers.',
    'zone.relationships.label': 'Relationships',
    'zone.relationships.bestUse': 'Schedule important conversations in stronger energy bands.',
    'zone.relationships.caution': 'Not a relationship outcome prediction.',
    'zone.relationships.rationale': 'Relational decisions benefit from communication clarity windows.',
    'zone.travel.label': 'Travel',
    'zone.travel.bestUse': 'Use travel for exploration when decisions are reversible.',
    'zone.travel.caution': 'Do not schedule irreversible moves solely around travel windows.',
    'zone.travel.rationale': 'Movement and context change can stimulate option quality.',
    'zone.wellbeing.label': 'Wellbeing',
    'zone.wellbeing.bestUse': 'Protect recovery before high-stakes calls.',
    'zone.wellbeing.caution': 'Not medical advice — schedule rest as a decision input.',
    'zone.wellbeing.rationale': 'Recovery windows affect decision quality under load.',
  },
  fa: {
    'blind.acts-too-quickly.description': 'سرعت کمک می‌کند — وقتی زیان سخت قابل برگشت است یک‌بار مکث کنید.',
    'blind.acts-too-quickly.label': 'عمل خیلی سریع',
    'blind.acts-too-quickly.mitigation': 'یک بازه تصمیم زمان‌بندی‌شده و یک اقدام پیش‌فرض برگشت‌پذیر تعیین کنید.',
    'blind.acts-too-quickly.trigger': 'ابهام بالا با مهلت نرم',
    'blind.avoids-conflict.description': 'ترجیح هماهنگی می‌تواند گفتگوهای سخت لازم را به تعویق بیندازد.',
    'blind.avoids-conflict.label': 'اجتناب از تعارض',
    'blind.avoids-conflict.mitigation': 'یک گفتگوی ضروری را نام ببرید و پیش از قفل کردن حرکت زمان‌بندی کنید.',
    'blind.avoids-conflict.trigger': 'اختلاف بین‌فردی حول تصمیم',
    'blind.context-switching.description': 'رشته‌های موازی قضاوت را رقیق می‌کنند؛ تصمیم‌ها را بر اساس حوزه دسته‌بندی کنید.',
    'blind.context-switching.label': 'تعویض زمینه',
    'blind.context-switching.mitigation': 'بر اساس حوزه دسته‌بندی کنید و پیش از باز کردن تصمیم بعدی یکی را ببندید.',
    'blind.context-switching.trigger': 'چندین تصمیم باز در یک روز',
    'blind.deferred-follow-through.description': 'بینش زود می‌آید؛ حلقه را با اقدام بعدی تاریخ‌دار ببندید.',
    'blind.deferred-follow-through.label': 'پیگیری به‌تعویق‌افتاده',
    'blind.deferred-follow-through.mitigation': 'تاریخ تقویم و مالک را به گام مشخص بعدی بچسبانید.',
    'blind.deferred-follow-through.trigger': 'آرامش پس از تصمیم',
    'blind.goes-solo-early.description': 'انگیزه مستقل می‌تواند ذی‌نفعی را که ریسک را کم می‌کند نادیده بگیرد.',
    'blind.goes-solo-early.label': 'خیلی زود تنها رفتن',
    'blind.goes-solo-early.mitigation': 'یک گفتگوی ضروری را نام ببرید و پیش از قفل کردن حرکت زمان‌بندی کنید.',
    'blind.goes-solo-early.trigger': 'اختلاف بین‌فردی حول تصمیم',
    'blind.overthinks.description': 'تحلیل اضافه می‌تواند حرکت‌های برگشت‌پذیری را که سریع‌تر آموزش می‌دهند به تأخیر بیندازد.',
    'blind.overthinks.label': 'زیاد فکر کردن',
    'blind.overthinks.mitigation': 'یک بازه تصمیم زمان‌بندی‌شده و یک اقدام پیش‌فرض برگشت‌پذیر تعیین کنید.',
    'blind.overthinks.trigger': 'ابهام بالا با مهلت نرم',
    'blind.perfectionism.description': 'استاندارد کیفیت زیر فشار بالا می‌رود؛ نقاط کنترل «به‌اندازه کافی خوب» تعریف کنید.',
    'blind.perfectionism.label': 'کمال‌گرایی',
    'blind.perfectionism.mitigation': 'پیش از اصلاح بیشتر، یک حداقل موفقیت قابل قبول بنویسید.',
    'blind.perfectionism.trigger': 'نتایج عمومی یا با دیده‌شدن بالا',
    'blind.risk-avoidance.description': 'احتیاط از شما محافظت می‌کند — همچنین یک آزمایش کنترل‌شده زمان‌بندی کنید.',
    'blind.risk-avoidance.label': 'اجتناب از ریسک',
    'blind.risk-avoidance.mitigation': 'آزمایش‌های برگشت‌پذیر را از تعهدهای برگشت‌ناپذیر در یک فهرست کتبی جدا کنید.',
    'blind.risk-avoidance.trigger': 'گزینه‌های پرزیان',
    'blind.surge-decisions.description': 'اوج انرژی می‌تواند تأمل را فشرده کند؛ روی تصمیم‌های برگشت‌ناپذیر یک شب بخوابید.',
    'blind.surge-decisions.label': 'تصمیم‌های اوج احساسی',
    'blind.surge-decisions.mitigation': 'آزمایش‌های برگشت‌پذیر را از تعهدهای برگشت‌ناپذیر در یک فهرست کتبی جدا کنید.',
    'blind.surge-decisions.trigger': 'فشار زمانی + احساس قوی',
    'communication.approach': 'پیش از بحث گزینه‌ها، تصمیم، معیارها و درخواست را در سه جمله بیان کنید.',
    'communication.conflict.align': 'هم‌راستایی می‌جوید؛ ممکن است رویارویی را تا اجبار منافع به تأخیر بیندازد',
    'communication.conflict.direct': 'مسائل را مستقیم مطرح می‌کند؛ ممکن است ریتم احساسی را کم‌وزن کند',
    'communication.env.flexible': 'فروم‌های انعطاف‌پذیر با اهداف صریح',
    'communication.env.prepared': '۱:۱ آماده‌شده یا گروه‌های کوچک متمرکز',
    'communication.listen.action': 'برای نیت و تکانه گوش می‌دهد؛ به‌سوی اقدام خلاصه می‌کند',
    'communication.listen.analytical': 'برای ساختار، ناسازگاری‌ها و معیارهای تصمیم گوش می‌دهد',
    'communication.persuade.ask': 'ابتدا درخواست روشن و مالکیت',
    'communication.persuade.evidence': 'ابتدا شواهد و معیارها',
    'communication.persuade.narrative': 'ابتدا روایت و گزینه‌ها',
    'communication.primary.direct': 'مستقیم و نتیجه‌محور',
    'communication.primary.relational': 'رابطه‌محور و غنی از زمینه',
    'communication.risk.brevity': 'ایجاز می‌تواند زمینه احساسی مورد نیاز دیگران را جا بگذارد',
    'communication.risk.criteria': 'معیارهای بیان‌نشده تصمیم توافق کاذب می‌سازند',
    'communication.risk.harmony': 'ترجیح هماهنگی می‌تواند مخالفت را دفن کند',
    'conf.blindSpots': 'برچسب‌های نقاط کور، الگوهای ریسک تصمیم هستند، نه تشخیص بالینی.',
    'conf.communication': 'سبک ارتباط مدلی برای پشتیبانی تصمیم در People و Julia است.',
    'conf.comparative': 'فقط سیگنال‌های مقایسه‌ای — نه پیش‌بینی قطعی.',
    'conf.complete': 'پروفایل از ورودی‌های کامل زمان‌بندی تولد ساخته شده است.',
    'conf.decisionStyle': 'اطمینان سبک تصمیم کامل بودن ورودی‌های زمان‌بندی تولد را دنبال می‌کند.',
    'conf.decisionStyle.limit': 'برچسب‌های سبک enumهای کنترل‌شده‌اند، نه ادعاهای آزاد شخصیت.',
    'conf.energy': 'باندهای انرژی نسبی‌اند، نه پیش‌بینی ساعتی.',
    'conf.energy.limit': 'باندها را زمان‌های تضمینی اوج عملکرد ندانید.',
    'conf.environment': 'توصیه‌های محیط از کیفیت قضاوت پشتیبانی می‌کنند، نه دستور محیط کار.',
    'conf.growth': 'حوزه‌های رشد توصیه‌های تمرین تصمیم‌اند، نه وعده خودیاری.',
    'conf.leadership': 'اینجا رهبری یعنی نفوذ و مسئولیت، نه عنوان شغلی.',
    'conf.learning': 'ترجیحات یادگیری از رشد مهارت تصمیم پشتیبانی می‌کنند، نه برچسب‌های تحصیلی.',
    'conf.opportunity': 'امتیازهای فرصت، قدرت نسبی بین حوزه‌ها هستند، نه پیش‌بینی.',
    'conf.opportunity.limit': 'به‌عنوان قطعیت نتایج تفسیر نکنید.',
    'conf.partial': 'پروفایل ناقص — برای افزایش اطمینان، تکمیل ورود اولیه را انجام دهید.',
    'conf.pressure': 'الگوهای فشار گرایش‌های مشتق از زمان‌بندی‌اند، نه ارزیابی بالینی.',
    'conf.strengths': 'سیگنال‌های نقاط قوت، الگوهای مقایسه‌ای مشتق‌شده از زمان‌بندی هستند.',
    'conf.work': 'سبک کار ریتم پشتیبانی تصمیم را توصیف می‌کند، نه تضمین بهره‌وری.',
    'decision-style.explanation': 'حالت اصلی {primary} است، با گرایش‌های ثانویه به سمت {secondary}. وضعیت ریسک {risk} است؛ سرعت معمولاً {speed} است. مشتق از لنگرهای زمان‌بندی تولد و فراداده پروفایل — مقایسه‌ای، نه پیش‌بینانه.',
    'decision-style.secondary.fallback': 'تنظیم انطباقی',
    'energy.explanation.adjusted': '، با تنظیم نرم بر اساس امتیاز زمان‌بندی امروز.',
    'energy.explanation.base': 'باندهای انرژی نسبی از لنگرهای زمان‌بندی تولد',
    'energy.explanation.full.adjusted': 'باندهای انرژی نسبی از لنگرهای زمان‌بندی تولد، با تنظیم نرم بر اساس امتیاز زمان‌بندی امروز.',
    'energy.explanation.full.noLive': 'باندهای انرژی نسبی از لنگرهای زمان‌بندی تولد. دقت ساعتی زنده جداگانه به موتور زمان‌بندی نیاز دارد.',
    'energy.explanation.noLive': '. دقت ساعتی زنده جداگانه به موتور زمان‌بندی نیاز دارد.',
    'energy.recovery.afternoon': 'بازنشانی اواخر بعدازظهر پیش از تعهدهای عصر',
    'energy.recovery.midday': 'مکث میانه بعدازظهر بین بلوک‌های تصمیم',
    'energy.recovery.morning': 'بافر اواخر صبح پس از تعهدهای اولیه',
    'env.collab.high': 'بالا برای تصمیم‌های بزرگ',
    'env.collab.selective': 'مشورت گزینشی',
    'env.distraction.high': 'بالا',
    'env.distraction.moderate': 'متوسط',
    'env.info.criteria': 'معیار و شواهد پیش از تعهد',
    'env.info.options': 'گزینه‌های روشن و گام بعدی برگشت‌پذیر',
    'env.pressure.high': 'متوسط–بالا',
    'env.pressure.low': 'کم–متوسط',
    'env.setting.collaborative': 'مشارکتی',
    'env.setting.flexible': 'انعطاف‌پذیر',
    'env.setting.quiet': 'آرام',
    'env.setting.remote': 'دورکار / کنترل‌شده',
    'env.setting.stable': 'فضای کاری پایدار',
    'env.setting.travel': 'سازگار با سفر',
    'env.setup': 'محیط آرام یا گروه کوچک آماده‌شده، معیار کتبی، یک آزمایش برگشت‌پذیر، و زمان مرور سخت.',
    'error.loadFailed': 'بارگذاری پروفایل هوش شخصی ممکن نشد.',
    'evidence.countOnly': 'فقط شمارش — تاریخچه خام در پروفایل جاسازی نشده است.',
    'evidence.derived': 'فقط از لنگرهای زمان‌بندی موجود پروفایل مشتق شده است.',
    'evidence.partial': 'پروفایل ناقص — ورودی‌های مفقود اطمینان را کاهش دادند.',
    'growth.blind-spot.area': 'نظارت نقطه کور اصلی',
    'growth.blind-spot.practice.unnamed': 'پیش از تصمیم، ریسک اصلی را در یک جمله نام ببرید.',
    'growth.blind-spot.reason': 'الگوی «{label}» زیر بار ظاهر می‌شود.',
    'growth.blind-spot.reason.unnamed': 'ریسک بی‌نام بازیابی پس از تصمیم را کند می‌کند.',
    'growth.blind-spot.review': 'دوهفته‌ای',
    'growth.blind-spot.success': 'یک نقطه کنترل صریح به تصمیم پرریسک بعدی وصل شده است.',
    'growth.conflict.area': 'تمرین تعارض مستقیم',
    'growth.conflict.practice': 'ماهی یک گفتگوی مستقیم آماده‌شده تمرین کنید.',
    'growth.conflict.reason': 'ترجیح هم‌راستایی می‌تواند اصطکاک لازم را به تأخیر بیندازد.',
    'growth.conflict.review': 'ماهانه',
    'growth.conflict.success': 'یادداشت‌های تصمیم حداقل یک ورودی مخالف دارند.',
    'growth.dissent.area': 'ورودی مخالف',
    'growth.dissent.practice': 'پیش از قفل کردن حرکت‌های بزرگ یک نظر مخالف دعوت کنید.',
    'growth.dissent.reason': 'انگیزه مستقل می‌تواند ذی‌نفعان کاهش‌دهنده ریسک را از دست بدهد.',
    'growth.protected.area': 'بلوک‌های تصمیم محافظت‌شده',
    'growth.protected.practice': 'در روزهای پرریسک یک بلوک تصمیم کارعمیق محافظت کنید.',
    'growth.protected.reason': 'بدون تمرکز بی‌وقفه کیفیت قضاوت افت می‌کند.',
    'growth.protected.review': 'هفتگی',
    'growth.protected.success': 'تقویم پیش از تصمیم‌های مهم یک بلوک تصمیم برچسب‌دار نشان می‌دهد.',
    'growth.reversible.area': 'تعهدهای برگشت‌پذیر-اول',
    'growth.reversible.practice': 'پیش از هر تعهد برگشت‌ناپذیر، یک آزمایش برگشت‌پذیر ۴۸ساعته تعریف کنید.',
    'growth.reversible.reason': 'حرکت‌های برگشت‌ناپذیر بدون آزمایش زیان را بالا می‌برند.',
    'growth.reversible.review': 'ماهانه',
    'growth.reversible.success': 'هر ثبت تصمیم مهم شامل گام آزمایش و تاریخ است.',
    'growth.review.area': 'عادت مرور تصمیم',
    'growth.review.practice': 'تصمیم‌های ذخیره‌شده را ماهانه مرور کنید: چه تغییر کرد در برابر چه توصیه کردید.',
    'growth.review.reason': 'بدون مرور، توصیه‌ها به مهارت تبدیل نمی‌شوند.',
    'growth.review.review': 'ماهانه',
    'growth.review.success': 'تاریخچه Vault یا Pathfinder یک یادداشت مرور تاریخ‌دار نشان می‌دهد.',
    'horizon.balanced': 'متعادل',
    'horizon.long-term': 'بلندمدت',
    'horizon.near-term': 'کوتاه‌مدت',
    'independence.collaborative': 'مشارکتی',
    'independence.independent': 'مستقل',
    'independence.selective': 'گزینشی',
    'leadership.development': 'در هر خلاصه تصمیمی که رهبری می‌کنید، بیان معیار و مالک بعدی را تمرین کنید.',
    'leadership.environment': 'مالکیت روشن، نشانه‌های موفقیت صریح، و فضای آزمایش‌های برگشت‌پذیر.',
    'leadership.primary.analyst': 'تحلیل‌گر',
    'leadership.primary.builder': 'سازنده',
    'leadership.primary.mentor': 'مربی',
    'leadership.primary.vision': 'چشم‌اندازمحور',
    'leadership.risk.analysis': 'تأخیر تحلیل زیر فوریت',
    'leadership.risk.conflict': 'اجتناب از تعارض',
    'leadership.risk.execution': 'اجرای کم‌مشخص',
    'leadership.risk.optimize': 'بهینه‌سازی بیش از حد ساخت پیش از هم‌راستایی',
    'leadership.secondary.adaptive': 'انطباقی',
    'leadership.secondary.operational': 'عملیاتی',
    'leadership.strength.align': 'نتایج مشترک را هم‌راستا می‌کند',
    'leadership.strength.contribution': 'مشارکت را دعوت می‌کند',
    'leadership.strength.destination': 'مقصد را تعیین می‌کند',
    'leadership.strength.evidence': 'با شواهد کیفیت تصمیم را بالا می‌برد',
    'leadership.strength.people': 'افراد را رشد می‌دهد',
    'leadership.strength.ships': 'پیشرفت را تحویل می‌دهد',
    'leadership.strength.systems': 'سیستم‌ها را در حرکت پالایش می‌کند',
    'leadership.strength.tradeoffs': 'بده‌بستان‌ها را روشن می‌کند',
    'learning.barrier.frameworks': 'جمع‌آوری چارچوب بدون کاربرد زنده',
    'learning.barrier.reflection': 'رد کردن تأمل پس از آزمایش‌ها',
    'learning.method.analytical': 'تحلیلی',
    'learning.method.discussion': 'بحث',
    'learning.method.experimentation': 'آزمایش',
    'learning.method.practical': 'عملی',
    'learning.method.reading': 'مطالعه',
    'learning.method.visual': 'نگاشت بصری',
    'learning.practice': 'ظرف ۴۸ ساعت پس از یادگیری به‌کار ببرید',
    'learning.processing.models': 'مدل‌هایی که موارد واقعی را توضیح می‌دهند',
    'learning.processing.real': 'ابتدا نسخه‌های کوچک واقعی',
    'learning.recommended': 'ابتدا {primary}، سپس {secondary} برای آزمودن فهم.',
    'learning.retention': 'پس از تمرین، بازتدریس یا یادداشت تصمیم کتبی',
    'legacy.blind.why': '{description} کاهش اثر: {mitigation}',
    'legacy.fast.label': 'سریع',
    'legacy.fast.why': 'وقتی ورودی‌ها روشن باشند سرعت تصمیم به سمت سریع متمایل است.',
    'legacy.patient.label': 'صبور',
    'legacy.patient.why': 'گرایش ریسک، ریتم سنجیده را ترجیح می‌دهد.',
    'legacy.riskBalanced.label': 'ریسک متعادل',
    'legacy.riskBalanced.why': 'گرایش ریسک: {risk}.',
    'limit.comparative': 'فقط پشتیبانی مقایسه‌ای تصمیم.',
    'limit.noLiveTiming': 'زمینه زمان‌بندی زنده در زمان ساخت تأمین نشده است.',
    'pressure.protocol': 'بخش برگشت‌ناپذیر را نام ببرید، گام بعدی را به اقدام برگشت‌پذیر کوچک کنید، و داخل باند انرژی قوی‌تر با نقطه کنترل تاریخ‌دار تصمیم بگیرید.',
    'pressure.recovery.default': 'یک فاصله کوتاه، سپس یک گام مشخص بعدی، ریتم را بازمی‌گرداند.',
    'pressure.recovery.morning': 'بازنشانی‌های آرام اولیه به‌علاوه فهرست اولویت کتبی کیفیت قضاوت را بازمی‌گرداند.',
    'pressure.response.action': 'به‌سوی اقدام شتاب می‌گیرد؛ ابهام می‌تواند مثل از دست رفتن تکانه حس شود.',
    'pressure.response.analytical': 'تمرکز را باریک می‌کند و داده بیشتری می‌جوید؛ فوریت می‌تواند مثل اطلاعات ناقص حس شود.',
    'pressure.risk.action': 'فشردن تأمل ریسک خطای برگشت‌ناپذیر را بالا می‌برد.',
    'pressure.risk.analytical': 'جمع‌آوری بیش از حد ورودی یادگیری برگشت‌پذیر را به تأخیر می‌اندازد.',
    'pressure.trigger.deadlines': 'مهلت‌های سخت با اطلاعات ناقص',
    'pressure.trigger.disagreement': 'اختلاف بین‌فردی',
    'pressure.trigger.irreversible': 'زیان برگشت‌ناپذیر بدون مسیر آزمایش',
    'pressure.trigger.silence': 'سکوت ذی‌نفع وقتی مالکیت روشن نیست',
    'risk.balanced': 'متعادل',
    'risk.bold': 'جسور',
    'risk.cautious': 'محتاط',
    'speed.deliberate': 'سنجیده',
    'speed.fast': 'سریع',
    'speed.measured': 'اندازه‌گیری‌شده',
    'strength.communication.application': 'پیش از گرفتن نظر، معیارهای تصمیم را در یک خلاصه کوتاه بیان کنید.',
    'strength.communication.description': 'شفافیت وقتی ایده‌ها گفته و با دیگران آزموده می‌شوند بهتر می‌شود.',
    'strength.communication.label': 'ارتباط',
    'strength.creativity.application': 'پیش از انتخاب دوتایی قبول/رد، یک گزینه سوم غیرآشکار بسازید.',
    'strength.creativity.description': 'وقتی محدودیت‌ها صریح باشند، گزینه‌های تازه ظاهر می‌شوند.',
    'strength.creativity.label': 'خلاقیت',
    'strength.decision-sequencing.application': 'پیش از هر تعهد سخت، یک آزمایش برگشت‌پذیر تاریخ‌دار الزامی کنید.',
    'strength.decision-sequencing.description': 'وقتی گام‌های برگشت‌ناپذیر بعد از آزمایش‌های برگشت‌پذیر بیایند، بهترین عملکرد را دارد.',
    'strength.decision-sequencing.label': 'توالی تصمیم',
    'strength.execution-focus.application': 'برای گام برگشت‌ناپذیر، یک بلوک بدون وقفه حفظ کنید.',
    'strength.execution-focus.description': 'بازه‌های تمرکز پایدار، برنامه را به کار تمام‌شده تبدیل می‌کنند.',
    'strength.execution-focus.label': 'تمرکز اجرایی',
    'strength.leadership.application': 'پیش از باز کردن بحث، مالک تصمیم و نشانه موفقیت را مشخص کنید.',
    'strength.leadership.description': 'تعیین جهت در شرایط اهداف روشن، حالت طبیعی شماست.',
    'strength.leadership.label': 'رهبری',
    'strength.learning-speed.application': 'برای یادگیری سریع‌تر از نظریه‌پردازی، نسخه کوچک واقعی از گزینه را اجرا کنید.',
    'strength.learning-speed.description': 'وقتی پای منافع واقعی در میان است، چارچوب‌های جدید را سریع جذب می‌کند.',
    'strength.learning-speed.label': 'سرعت یادگیری',
    'strength.long-term-planning.application': 'هنگام رتبه‌بندی گزینه‌ها بر اساس اثر ۹۰روزه، پیش از تعهد سرمایه یا اعتبار، از این توان استفاده کنید.',
    'strength.long-term-planning.description': 'گزینه‌ها را بر اساس نتایج چندمرحله‌ای می‌چیند، نه یک حرکت تکی.',
    'strength.long-term-planning.label': 'برنامه‌ریزی بلندمدت',
    'strength.negotiation.application': 'پیش از چانه‌زنی، بایدهای هر طرف را فهرست کنید.',
    'strength.negotiation.description': 'وقتی منافع نگاشت شوند، بده‌بستان‌ها روشن‌تر می‌شوند.',
    'strength.negotiation.label': 'مذاکره',
    'strength.pattern-recognition.application': 'پیش از انتخاب، دو تصمیم مشابه قبلی را نگاشت کنید.',
    'strength.pattern-recognition.description': 'پیش از اقدام، سیگنال‌ها را در بافت‌های مختلف به هم وصل می‌کند.',
    'strength.pattern-recognition.label': 'تشخیص الگو',
    'strength.systems-thinking.application': 'پیش از بهینه‌سازی یک اهرم، ریسک‌های وابستگی را ترسیم کنید.',
    'strength.systems-thinking.description': 'پیش از بهینه‌سازی یک قطعه، تعامل اجزا را می‌بیند.',
    'strength.systems-thinking.label': 'تفکر سیستمی',
    'style.adaptive': 'انطباقی',
    'style.analytical': 'تحلیلی',
    'style.cautious': 'محتاط',
    'style.collaborative': 'مشارکتی',
    'style.execution-focused': 'نتیجه‌محور',
    'style.exploratory': 'اکتشافی',
    'style.intuitive': 'شهودی',
    'style.strategic': 'راهبردی',
    'style.decisive': 'قاطع',
    'style.risk-aware': 'ریسک‌آگاه',
    'summary.body': 'شما در حالت {styles} تصمیم می‌گیرید و نقاط قوت برجسته‌تان در {strengthLabels} است. رهبری معمولاً به سمت {leadership} گرایش دارد و ریتم کار {work} را ترجیح می‌دهد. پیش از تعهدهای برگشت‌ناپذیر، آزمایش‌های برگشت‌پذیر اجرا کنید و تصمیم‌های پرریسک را در بازه‌های انرژی قوی‌تر زمان‌بندی کنید. این‌ها سیگنال‌های مقایسه‌ای پشتیبانی تصمیم هستند، نه پیش‌بینی.',
    'work.change.high': 'بالا — تازگی مفید می‌جوید',
    'work.change.measured': 'اندازه‌گیری‌شده — تغییر متوالی را ترجیح می‌دهد',
    'work.collab.owner': 'مالک‌محور',
    'work.collab.team': 'تیم‌محور',
    'work.env.deep': 'بلوک‌های کم‌وقفه برای تصمیم‌های پرریسک',
    'work.env.flexible': 'فضای انعطاف‌پذیر با ورودی‌های تصمیم تمیز',
    'work.focus.deep': 'کار عمیق',
    'work.focus.flexible': 'تعویض انعطاف‌پذیر',
    'work.rhythm.frontload': 'کار حیاتی را جلو بیندازید',
    'work.rhythm.lateday': 'پالایش اواخر روز',
    'work.rhythm.midday': 'اوج اجرا در میانه روز',
    'work.risk.interruptions': 'وقفه کیفیت قضاوت را فرو می‌ریزد',
    'work.risk.irreversible': 'شروع کار برگشت‌ناپذیر پیش از آزمایش برگشت‌پذیر',
    'work.risk.switching': 'تعویض زمینه بدون دسته‌بندی',
    'work.structure.adaptive': 'ساختار انطباقی',
    'work.structure.plans': 'برنامه‌های ساخت‌یافته',
    'zone.business.label': 'کسب‌وکار',
    'zone.business.bestUse': 'پیش از تعهد کامل، پیشنهادها را آزمایش کنید.',
    'zone.business.caution': 'از راه‌اندازی همه‌یا‌هیچ در روزهای آمادگی پایین پرهیز کنید.',
    'zone.business.rationale': 'الگوی پروفایل از تولید گزینه و راه‌اندازی مرحله‌ای پشتیبانی می‌کند.',
    'zone.career.label': 'شغل',
    'zone.career.bestUse': 'یک اهرم شغلی را با مرور هفتگی اولویت دهید.',
    'zone.career.caution': 'امتیاز را پیش‌بینی ارتقا ندانید.',
    'zone.career.rationale': 'لنگرهای زمان‌بندی پیشرفت ساخت‌یافته در برابر اهداف روشن نقش را پشتیبانی می‌کنند.',
    'zone.creativity.label': 'خلاقیت',
    'zone.creativity.bestUse': 'پیش از انتخاب دوتایی یک گزینه سوم بسازید.',
    'zone.creativity.caution': 'نوآوری بدون نقاط کنترل ریسک اجرا را بالا می‌برد.',
    'zone.creativity.rationale': 'باند خلاق از قاب‌بندی جایگزین زیر محدودیت پشتیبانی می‌کند.',
    'zone.leadership.label': 'رهبری',
    'zone.leadership.bestUse': 'با بیان معیار و مالک بعدی، تصمیم‌ها را هدایت کنید.',
    'zone.leadership.caution': 'اینجا رهبری یعنی نفوذ، نه عنوان شغلی.',
    'zone.leadership.rationale': 'الگوهای نفوذ شفاف‌سازی مالکیت و نتایج را ترجیح می‌دهند.',
    'zone.learning.label': 'یادگیری',
    'zone.learning.bestUse': 'مطالعه را با یک آزمایش کاربردی کوچک جفت کنید.',
    'zone.learning.caution': 'تکمیل همچنان به طراحی تمرین وابسته است.',
    'zone.learning.rationale': 'سیگنال‌های سرعت یادگیری / الگو از کسب مهارت پشتیبانی می‌کنند.',
    'zone.money.label': 'پول',
    'zone.money.bestUse': 'پیش از تخصیص، حد زیان را تعیین کنید.',
    'zone.money.caution': 'امتیاز مقایسه‌ای است — نه توصیه بازار.',
    'zone.money.rationale': 'باند تحلیلی از تصمیم‌های سرمایهٔ سنجیده پشتیبانی می‌کند.',
    'zone.networking.label': 'شبکه‌سازی',
    'zone.networking.bestUse': 'پیش از قفل‌های بزرگ یک نظر مخالف بخواهید.',
    'zone.networking.caution': 'حجم تماس‌ها ≠ کیفیت تصمیم.',
    'zone.networking.rationale': 'گرایش مشارکتی سیگنال از همتایان مورد اعتماد را بهبود می‌دهد.',
    'zone.relationships.label': 'روابط',
    'zone.relationships.bestUse': 'گفتگوهای مهم را در باندهای انرژی قوی‌تر زمان‌بندی کنید.',
    'zone.relationships.caution': 'پیش‌بینی نتیجه رابطه نیست.',
    'zone.relationships.rationale': 'تصمیم‌های رابطه‌ای از پنجره‌های شفافیت ارتباطی سود می‌برند.',
    'zone.travel.label': 'سفر',
    'zone.travel.bestUse': 'وقتی تصمیم‌ها برگشت‌پذیرند از سفر برای اکتشاف استفاده کنید.',
    'zone.travel.caution': 'حرکت‌های برگشت‌ناپذیر را صرفاً حول پنجره‌های سفر زمان‌بندی نکنید.',
    'zone.travel.rationale': 'حرکت و تغییر زمینه می‌تواند کیفیت گزینه را تحریک کند.',
    'zone.wellbeing.label': 'بهزیستی',
    'zone.wellbeing.bestUse': 'پیش از تصمیم‌های پرریسک از بازیابی محافظت کنید.',
    'zone.wellbeing.caution': 'توصیه پزشکی نیست — استراحت را به‌عنوان ورودی تصمیم زمان‌بندی کنید.',
    'zone.wellbeing.rationale': 'پنجره‌های بازیابی کیفیت تصمیم زیر بار را تحت تأثیر قرار می‌دهند.',
  },
  ar: {
    'blind.acts-too-quickly.description': 'السرعة تساعد — توقّف مرة عندما يصعب عكس الضرر.',
    'blind.acts-too-quickly.label': 'التصرّف بسرعة مفرطة',
    'blind.acts-too-quickly.mitigation': 'حدّد نافذة قرار موقوتة وإجراء افتراضياً قابلاً للعكس.',
    'blind.acts-too-quickly.trigger': 'غموض عالٍ مع موعد مرن',
    'blind.avoids-conflict.description': 'تفضيل الانسجام قد يؤجّل محادثات صعبة ضرورية.',
    'blind.avoids-conflict.label': 'تجنّب الصراع',
    'blind.avoids-conflict.mitigation': 'سمِّ محادثة مطلوبة واحدة وجدولها قبل قفل الخطوة.',
    'blind.avoids-conflict.trigger': 'خلاف بين الأشخاص حول القرار',
    'blind.context-switching.description': 'الخيوط المتوازية تضعف الحكم؛ جمّع القرارات حسب المجال.',
    'blind.context-switching.label': 'تبديل السياق',
    'blind.context-switching.mitigation': 'جمّع حسب المجال وأغلق قراراً قبل فتح آخر.',
    'blind.context-switching.trigger': 'عدة قرارات مفتوحة في يوم واحد',
    'blind.deferred-follow-through.description': 'البصيرة تأتي مبكراً؛ أغلق الحلقة بخطوة تالية مؤرّخة.',
    'blind.deferred-follow-through.label': 'متابعة مؤجّلة',
    'blind.deferred-follow-through.mitigation': 'ألحق تاريخاً في التقويم ومالكاً بالخطوة الملموسة التالية.',
    'blind.deferred-follow-through.trigger': 'ارتياح ما بعد القرار',
    'blind.goes-solo-early.description': 'الدافع المستقل قد يتجاوز طرفاً يقلّل المخاطر.',
    'blind.goes-solo-early.label': 'الانفراد مبكراً جداً',
    'blind.goes-solo-early.mitigation': 'سمِّ محادثة مطلوبة واحدة وجدولها قبل قفل الخطوة.',
    'blind.goes-solo-early.trigger': 'خلاف بين الأشخاص حول القرار',
    'blind.overthinks.description': 'التحليل الزائد قد يؤخّر حركات قابلة للعكس تعلّم أسرع.',
    'blind.overthinks.label': 'الإفراط في التفكير',
    'blind.overthinks.mitigation': 'حدّد نافذة قرار موقوتة وإجراء افتراضياً قابلاً للعكس.',
    'blind.overthinks.trigger': 'غموض عالٍ مع موعد مرن',
    'blind.perfectionism.description': 'معايير الجودة ترتفع تحت الضغط؛ عرّف نقاط تحقق «جيد بما يكفي».',
    'blind.perfectionism.label': 'الكمال',
    'blind.perfectionism.mitigation': 'اكتب حداً أدنى للنجاح قبل مواصلة التحسين.',
    'blind.perfectionism.trigger': 'نتائج عامة أو عالية الظهور',
    'blind.risk-avoidance.description': 'الحذر يحميك — جدول أيضاً تجربة مضبوطة واحدة.',
    'blind.risk-avoidance.label': 'تجنّب المخاطر',
    'blind.risk-avoidance.mitigation': 'افصل التجارب القابلة للعكس عن الالتزامات غير القابلة للعكس في قائمة مكتوبة.',
    'blind.risk-avoidance.trigger': 'خيارات ثقيلة الجانب السلبي',
    'blind.surge-decisions.description': 'قفزات الطاقة قد تضغط التأمل؛ نم على القرارات غير القابلة للعكس.',
    'blind.surge-decisions.label': 'قرارات ذروة عاطفية',
    'blind.surge-decisions.mitigation': 'افصل التجارب القابلة للعكس عن الالتزامات غير القابلة للعكس في قائمة مكتوبة.',
    'blind.surge-decisions.trigger': 'ضغط زمني + مشاعر قوية',
    'communication.approach': 'اذكر القرار والمعايير والطلب في ثلاث جمل قبل مناقشة الخيارات.',
    'communication.conflict.align': 'يسعى للتوافق؛ قد يؤجّل المواجهة حتى تفرض الرهانات ذلك',
    'communication.conflict.direct': 'يعالج القضايا مباشرة؛ قد يقلّل إيقاع المشاعر',
    'communication.env.flexible': 'منتديات مرنة بأهداف صريحة',
    'communication.env.prepared': 'لقاءات ١:١ مُعدّة أو مجموعات صغيرة مركّزة',
    'communication.listen.action': 'يستمع للنية والزخم؛ يلخّص نحو الفعل',
    'communication.listen.analytical': 'يستمع للبنية والتناقضات ومعايير القرار',
    'communication.persuade.ask': 'طلب واضح وملكية أولاً',
    'communication.persuade.evidence': 'الأدلة والمعايير أولاً',
    'communication.persuade.narrative': 'السرد والخيارات أولاً',
    'communication.primary.direct': 'مباشر وموجّه للنتيجة',
    'communication.primary.relational': 'علائقي وغني بالسياق',
    'communication.risk.brevity': 'الإيجاز قد يتجاوز السياق العاطفي الذي يحتاجه الآخرون',
    'communication.risk.criteria': 'معايير قرار غير مذكورة تخلق اتفاقاً زائفاً',
    'communication.risk.harmony': 'تفضيل الانسجام قد يدفن الخلاف',
    'conf.blindSpots': 'تسميات النقاط العمياء أنماط مخاطر قرار وليست تشخيصات.',
    'conf.communication': 'أسلوب التواصل نموذج لدعم القرار لـ People و Julia.',
    'conf.comparative': 'إشارات مقارنة فقط — وليست تنبؤاً حتمياً.',
    'conf.complete': 'بُني الملف من مدخلات توقيت الميلاد الكاملة.',
    'conf.decisionStyle': 'ثقة أسلوب القرار تتبع اكتمال مدخلات توقيت الميلاد.',
    'conf.decisionStyle.limit': 'تسميات الأسلوب تعدادات مضبوطة وليست ادعاءات شخصية حرّة.',
    'conf.energy': 'نطاقات الطاقة نسبية وليست توقعات على مستوى الساعة.',
    'conf.energy.limit': 'لا تعامل النطاقات كأوقات أداء ذروة مضمونة.',
    'conf.environment': 'توصيات البيئة تدعم جودة الحكم لا أوامر مكان العمل.',
    'conf.growth': 'مجالات النمو توصيات ممارسة قرار وليست وعود تطوير ذاتي.',
    'conf.leadership': 'القيادة هنا تعني التأثير والمسؤولية لا المسمى الوظيفي.',
    'conf.learning': 'تفضيلات التعلّم تدعم نمو مهارة القرار لا تسميات أكاديمية.',
    'conf.opportunity': 'درجات الفرصة نقاط قوة نسبية عبر المجالات وليست توقعات.',
    'conf.opportunity.limit': 'لا تفسّرها كيقين من النتائج.',
    'conf.partial': 'ملف جزئي — أكمل الإعداد لرفع الثقة.',
    'conf.pressure': 'أنماط الضغط ميول مشتقة من التوقيت وليست تقييمات سريرية.',
    'conf.strengths': 'إشارات نقاط القوة أنماط مقارنة مشتقة من التوقيت.',
    'conf.work': 'أسلوب العمل يصف إيقاع دعم القرار لا ضمانات إنتاجية.',
    'decision-style.explanation': 'الوضع الأساسي هو {primary}، مع ميول ثانوية نحو {secondary}. موقف المخاطر {risk}؛ والإيقاع يميل إلى {speed}. مشتق من مراسي توقيت الميلاد وبيانات الملف — مقارن وليس تنبؤياً.',
    'decision-style.secondary.fallback': 'تعديل تكيّفي',
    'energy.explanation.adjusted': '، معدّلة بلطف بدرجة توقيت اليوم.',
    'energy.explanation.base': 'نطاقات طاقة نسبية من مراسي توقيت الميلاد',
    'energy.explanation.full.adjusted': 'نطاقات طاقة نسبية من مراسي توقيت الميلاد، معدّلة بلطف بدرجة توقيت اليوم.',
    'energy.explanation.full.noLive': 'نطاقات طاقة نسبية من مراسي توقيت الميلاد. الدقة الساعية المباشرة تتطلّب محرّك التوقيت منفصلاً.',
    'energy.explanation.noLive': '. الدقة الساعية المباشرة تتطلّب محرّك التوقيت منفصلاً.',
    'energy.recovery.afternoon': 'إعادة ضبط أواخر بعد الظهر قبل التزامات المساء',
    'energy.recovery.midday': 'توقف منتصف بعد الظهر بين كتل القرار',
    'energy.recovery.morning': 'هامش أواخر الصباح بعد الالتزامات المبكرة',
    'env.collab.high': 'عالٍ للقرارات الكبرى',
    'env.collab.selective': 'استشارة انتقائية',
    'env.distraction.high': 'عالٍ',
    'env.distraction.moderate': 'متوسط',
    'env.info.criteria': 'معايير وأدلة قبل الالتزام',
    'env.info.options': 'خيارات واضحة وخطوة تالية قابلة للعكس',
    'env.pressure.high': 'متوسط–عالٍ',
    'env.pressure.low': 'منخفض–متوسط',
    'env.setting.collaborative': 'تعاوني',
    'env.setting.flexible': 'مرن',
    'env.setting.quiet': 'هادئ',
    'env.setting.remote': 'عن بُعد / مضبوط',
    'env.setting.stable': 'مساحة عمل مستقرة',
    'env.setting.travel': 'مناسب للسفر',
    'env.setup': 'إعداد هادئ أو مجموعة صغيرة مُعدّة، معايير مكتوبة، تجربة قابلة للعكس واحدة، ووقت مراجعة صارم.',
    'error.loadFailed': 'تعذّر تحميل ملف الذكاء الشخصي.',
    'evidence.countOnly': 'العدّ فقط — التاريخ الخام غير مضمّن في الملف.',
    'evidence.derived': 'مشتقة فقط من مراسي توقيت الملف المتاحة.',
    'evidence.partial': 'ملف جزئي — المدخلات الناقصة خفّضت الثقة.',
    'growth.blind-spot.area': 'مراقبة النقطة العمياء الأساسية',
    'growth.blind-spot.practice.unnamed': 'سمِّ أعلى مخاطرة لديك بجملة واحدة قبل القرار.',
    'growth.blind-spot.reason': 'يظهر نمط «{label}» تحت الحمل.',
    'growth.blind-spot.reason.unnamed': 'مخاطرة بلا اسم تبطئ التعافي بعد القرارات.',
    'growth.blind-spot.review': 'كل أسبوعين',
    'growth.blind-spot.success': 'نقطة تحقق صريحة مرفقة بالقرار التالي عالي المخاطر.',
    'growth.conflict.area': 'ممارسة الصراع المباشر',
    'growth.conflict.practice': 'مارس محادثة مباشرة واحدة مُعدّة كل شهر.',
    'growth.conflict.reason': 'تفضيل التوافق قد يؤخّر الاحتكاك الضروري.',
    'growth.conflict.review': 'شهرياً',
    'growth.conflict.success': 'ملاحظات القرار تتضمن مدخلاً مخالفاً واحداً على الأقل.',
    'growth.dissent.area': 'مدخل مخالف',
    'growth.dissent.practice': 'ادعُ رأياً مخالفاً واحداً قبل قفل الخطوات الكبرى.',
    'growth.dissent.reason': 'الدافع المستقل قد يفوّت أطرافاً تقلّل المخاطر.',
    'growth.protected.area': 'كتل قرار محمية',
    'growth.protected.practice': 'احمِ كتلة قرار عمل عميق في الأيام عالية المخاطر.',
    'growth.protected.reason': 'تنخفض جودة الحكم بلا تركيز متواصل.',
    'growth.protected.review': 'أسبوعياً',
    'growth.protected.success': 'يُظهر التقويم كتلة قرار موسومة قبل القرارات الكبرى.',
    'growth.reversible.area': 'التزامات قابلة للعكس أولاً',
    'growth.reversible.practice': 'عرّف تجربة قابلة للعكس لمدة ٤٨ ساعة قبل أي التزام غير قابل للعكس.',
    'growth.reversible.reason': 'الحركات غير القابلة للعكس بلا تجارب ترفع الجانب السلبي.',
    'growth.reversible.review': 'شهرياً',
    'growth.reversible.success': 'كل سجل قرار رئيسي يتضمن خطوة تجربة وتاريخاً.',
    'growth.review.area': 'عادة مراجعة القرار',
    'growth.review.practice': 'راجع القرارات المحفوظة شهرياً: ما تغيّر مقابل ما أوصيت به.',
    'growth.review.reason': 'بلا مراجعة لا تتحول التوصيات إلى مهارة.',
    'growth.review.review': 'شهرياً',
    'growth.review.success': 'تاريخ Vault أو Pathfinder يُظهر ملاحظة مراجعة مؤرّخة.',
    'horizon.balanced': 'متوازن',
    'horizon.long-term': 'طويل الأمد',
    'horizon.near-term': 'قصير الأمد',
    'independence.collaborative': 'تعاوني',
    'independence.independent': 'مستقل',
    'independence.selective': 'انتقائي',
    'leadership.development': 'تمرّن على بيان المعايير والمالك التالي في كل موجز قرار تقوده.',
    'leadership.environment': 'ملكية واضحة وإشارات نجاح صريحة ومساحة لتجارب قابلة للعكس.',
    'leadership.primary.analyst': 'محلل',
    'leadership.primary.builder': 'بانٍ',
    'leadership.primary.mentor': 'مرشد',
    'leadership.primary.vision': 'مدفوع بالرؤية',
    'leadership.risk.analysis': 'تأخير التحليل تحت الإلحاح',
    'leadership.risk.conflict': 'تجنّب الصراع',
    'leadership.risk.execution': 'تنفيذ غير محدّد بما يكفي',
    'leadership.risk.optimize': 'إفراط في تحسين البناء قبل التوافق',
    'leadership.secondary.adaptive': 'تكيّفي',
    'leadership.secondary.operational': 'تشغيلي',
    'leadership.strength.align': 'يحاذي النتائج المشتركة',
    'leadership.strength.contribution': 'يدعو للمساهمة',
    'leadership.strength.destination': 'يحدّد الوجهة',
    'leadership.strength.evidence': 'يرفع جودة القرار بالأدلة',
    'leadership.strength.people': 'يطوّر الناس',
    'leadership.strength.ships': 'يسلّم التقدّم',
    'leadership.strength.systems': 'يهذّب الأنظمة أثناء الحركة',
    'leadership.strength.tradeoffs': 'يوضّح المقايضات',
    'learning.barrier.frameworks': 'جمع أطر بلا تطبيق حي',
    'learning.barrier.reflection': 'تجاوز التأمل بعد التجارب',
    'learning.method.analytical': 'تحليلي',
    'learning.method.discussion': 'نقاش',
    'learning.method.experimentation': 'تجريب',
    'learning.method.practical': 'عملي',
    'learning.method.reading': 'قراءة',
    'learning.method.visual': 'رسم بصري',
    'learning.practice': 'طبّق خلال ٤٨ ساعة من التعلّم',
    'learning.processing.models': 'نماذج تفسّر حالات حقيقية',
    'learning.processing.real': 'نسخ حقيقية صغيرة أولاً',
    'learning.recommended': '{primary} أولاً ثم {secondary} لاختبار الفهم.',
    'learning.retention': 'إعادة تعليم أو ملاحظة قرار مكتوبة بعد الممارسة',
    'legacy.blind.why': '{description} التخفيف: {mitigation}',
    'legacy.fast.label': 'سريع',
    'legacy.fast.why': 'يميل سرعة القرار إلى السرعة عندما تكون المدخلات واضحة.',
    'legacy.patient.label': 'صبور',
    'legacy.patient.why': 'توجه المخاطر يفضّل إيقاعاً متروياً.',
    'legacy.riskBalanced.label': 'مخاطر متوازنة',
    'legacy.riskBalanced.why': 'توجه المخاطر: {risk}.',
    'limit.comparative': 'دعم قرار مقارن فقط.',
    'limit.noLiveTiming': 'لم يُزوَّد سياق توقيت مباشر عند البناء.',
    'pressure.protocol': 'سمِّ الجزء غير القابل للعكس، صغّر الخطوة التالية إلى فعل قابل للعكس، وقرّر داخل نطاق طاقة أقوى مع نقطة تحقق مؤرّخة.',
    'pressure.recovery.default': 'ابتعاد قصير ثم خطوة تالية ملموسة واحدة تستعيد الإيقاع.',
    'pressure.recovery.morning': 'إعادة ضبط هادئة مبكرة مع قائمة أولويات مكتوبة تستعيد جودة الحكم.',
    'pressure.response.action': 'يتسارع نحو الفعل؛ قد يبدو الغموض كفقدان زخم.',
    'pressure.response.analytical': 'يضيّق التركيز ويطلب مزيداً من البيانات؛ قد تبدو العجلة كمعلومات ناقصة.',
    'pressure.risk.action': 'ضغط التأمل يزيد مخاطر الخطأ غير القابل للعكس.',
    'pressure.risk.analytical': 'جمع مدخلات زائد يؤخّر التعلّم القابل للعكس.',
    'pressure.trigger.deadlines': 'مواعيد صارمة بمعلومات ناقصة',
    'pressure.trigger.disagreement': 'خلاف بين الأشخاص',
    'pressure.trigger.irreversible': 'جانب سلبي غير قابل للعكس بلا مسار تجربة',
    'pressure.trigger.silence': 'صمت الأطراف عندما تكون الملكية غير واضحة',
    'risk.balanced': 'متوازن',
    'risk.bold': 'جريء',
    'risk.cautious': 'حذر',
    'speed.deliberate': 'متروٍّ',
    'speed.fast': 'سريع',
    'speed.measured': 'مقيس',
    'strength.communication.application': 'أظهر معايير القرار في موجز قصير قبل طلب المدخلات.',
    'strength.communication.description': 'تتحسّن الوضوح عندما تُقال الأفكار وتُختبر مع الآخرين.',
    'strength.communication.label': 'التواصل',
    'strength.creativity.application': 'افرض خياراً ثالثاً غير واضح قبل الاختيار الثنائي قبول/رفض.',
    'strength.creativity.description': 'تظهر خيارات جديدة عندما تكون القيود صريحة.',
    'strength.creativity.label': 'الإبداع',
    'strength.decision-sequencing.application': 'اشترط تجربة قابلة للعكس مؤرّخة قبل أي التزام يصعب عكسه.',
    'strength.decision-sequencing.description': 'يؤدي أفضل عندما تتبع الخطوات غير القابلة للعكس تجارب قابلة للعكس.',
    'strength.decision-sequencing.label': 'تسلسل القرار',
    'strength.execution-focus.application': 'احمِ كتلة غير منقطعة للخطوة غير القابلة للعكس.',
    'strength.execution-focus.description': 'نوافذ التركيز المستدام تحوّل الخطط إلى عمل مكتمل.',
    'strength.execution-focus.label': 'التركيز على التنفيذ',
    'strength.leadership.application': 'حدّد مالك القرار وإشارة النجاح قبل فتح النقاش.',
    'strength.leadership.description': 'تحديد الاتجاه وضع طبيعي تحت أهداف واضحة.',
    'strength.leadership.label': 'القيادة',
    'strength.learning-speed.application': 'نفّذ نسخة صغيرة حقيقية من الخيار لتتعلّم أسرع من التنظير.',
    'strength.learning-speed.description': 'يمتص الأطر الجديدة بسرعة عندما تكون الرهانات حقيقية.',
    'strength.learning-speed.label': 'سرعة التعلّم',
    'strength.long-term-planning.application': 'استخدمه عند ترتيب الخيارات حسب أثر ٩٠ يوماً قبل الالتزام برأس مال أو سمعة.',
    'strength.long-term-planning.description': 'يصوغ الخيارات حول نتائج متعددة الخطوات بدل حركة واحدةحدة.',
    'strength.long-term-planning.label': 'التخطيط طويل الأمد',
    'strength.negotiation.application': 'اسرد ضروريات كل طرف قبل المساومة على القرار.',
    'strength.negotiation.description': 'تتضح المقايضات عندما تُرسم المصالح.',
    'strength.negotiation.label': 'التفاوض',
    'strength.pattern-recognition.application': 'ارسم قرارين سابقين مماثلين قبل الاختيار.',
    'strength.pattern-recognition.description': 'يربط الإشارات عبر السياقات قبل التصرّف.',
    'strength.pattern-recognition.label': 'تمييز الأنماط',
    'strength.systems-thinking.application': 'ارسم مخاطر التبعيات قبل تحسين رافعة واحدةحدة.',
    'strength.systems-thinking.description': 'يرى تفاعل الأجزاء قبل تحسين جزء واحد.',
    'strength.systems-thinking.label': 'التفكير النظمي',
    'style.adaptive': 'تكيّفي',
    'style.analytical': 'تحليلي',
    'style.cautious': 'حذر',
    'style.collaborative': 'تعاوني',
    'style.execution-focused': 'يركّز على التنفيذ',
    'style.exploratory': 'استكشافي',
    'style.intuitive': 'حدسي',
    'style.strategic': 'استراتيجي',
    'style.decisive': 'حاسم',
    'style.risk-aware': 'واعٍ بالمخاطر',
    'summary.body': 'تقرّر بأسلوب {styles}، مع نقاط قوة بارزة في {strengthLabels}. يميل أسلوب القيادة نحو {leadership}، ويفضّل إيقاع العمل {work}. استخدم تجارب قابلة للعكس قبل الالتزامات غير القابلة للعكس، وجدول القرارات عالية المخاطر ضمن نطاقات طاقة أقوى. هذه إشارات مقارنة لدعم القرار وليست تنبؤات.',
    'work.change.high': 'عالٍ — يبحث عن جدة مفيدة',
    'work.change.measured': 'مقيس — يفضّل تغييراً متسلسلاً',
    'work.collab.owner': 'مدفوع بالمالك',
    'work.collab.team': 'موجّه للفريق',
    'work.env.deep': 'كتل قليلة المقاطعة للقرارات عالية المخاطر',
    'work.env.flexible': 'مساحة مرنة بمدخلات قرار نظيفة',
    'work.focus.deep': 'عمل عميق',
    'work.focus.flexible': 'تبديل مرن',
    'work.rhythm.frontload': 'قدّم العمل الحرج أولاً',
    'work.rhythm.lateday': 'صقل في أواخر اليوم',
    'work.rhythm.midday': 'ذروة تنفيذ منتصف اليوم',
    'work.risk.interruptions': 'المقاطعات تنهار جودة الحكم',
    'work.risk.irreversible': 'بدء عمل غير قابل للعكس قبل تجربة قابلة للعكس',
    'work.risk.switching': 'تبديل سياق بلا تجميع',
    'work.structure.adaptive': 'بنية تكيّفية',
    'work.structure.plans': 'خطط منظّمة',
    'zone.business.label': 'الأعمال',
    'zone.business.bestUse': 'جرّب العروض قبل الالتزام الكامل.',
    'zone.business.caution': 'تجنّب الإطلاقات الكلّ أو لا شيء في أيام جاهزية منخفضة.',
    'zone.business.rationale': 'نمط الملف يدعم توليد الخيارات والإطلاقات المرحلية.',
    'zone.career.label': 'المهنة',
    'zone.career.bestUse': 'أعطِ أولوية لرافعة مهنية واحدة مع مراجعة أسبوعية.',
    'zone.career.caution': 'لا تعامل الدرجة كتوقّع ترقية.',
    'zone.career.rationale': 'مراسي التوقيت تفضّل تقدماً منظماً تجاه أهداف دور واضحة.',
    'zone.creativity.label': 'الإبداع',
    'zone.creativity.bestUse': 'افرض خياراً ثالثاً قبل الاختيارات الثنائية.',
    'zone.creativity.caution': 'الجدة بلا نقاط تحقق تزيد مخاطر التنفيذ.',
    'zone.creativity.rationale': 'النطاق الإبداعي يدعم إطاراً بديلاً تحت القيود.',
    'zone.leadership.label': 'القيادة',
    'zone.leadership.bestUse': 'قد القرارات ببيان المعايير والمالك التالي.',
    'zone.leadership.caution': 'القيادة هنا تعني التأثير لا المسمى الوظيفي.',
    'zone.leadership.rationale': 'أنماط التأثير تفضّل توضيح الملكية والنتائج.',
    'zone.learning.label': 'التعلّم',
    'zone.learning.bestUse': 'اربط الدراسة بتجربة تطبيقية صغيرة.',
    'zone.learning.caution': 'الإكمال ما زال يعتمد على تصميم الممارسة.',
    'zone.learning.rationale': 'إشارات سرعة التعلّم / الأنماط تدعم اكتساب المهارات.',
    'zone.money.label': 'المال',
    'zone.money.bestUse': 'حدّد حدود الجانب السلبي قبل التخصيص.',
    'zone.money.caution': 'الدرجة مقارنة — وليست نصيحة سوق.',
    'zone.money.rationale': 'النطاق التحليلي يدعم قرارات رأس مال متروية.',
    'zone.networking.label': 'التواصل',
    'zone.networking.bestUse': 'اطلب رأياً مخالفاً واحداً قبل الأقفال الكبرى.',
    'zone.networking.caution': 'حجم الاتصالات ≠ جودة القرار.',
    'zone.networking.rationale': 'الميل التعاوني يحسّن الإشارة من أقران موثوقين.',
    'zone.relationships.label': 'العلاقات',
    'zone.relationships.bestUse': 'جدول المحادثات المهمة في نطاقات طاقة أقوى.',
    'zone.relationships.caution': 'ليست توقّعاً لنتيجة العلاقة.',
    'zone.relationships.rationale': 'قرارات العلاقات تستفيد من نوافذ وضوح التواصل.',
    'zone.travel.label': 'السفر',
    'zone.travel.bestUse': 'استخدم السفر للاستكشاف عندما تكون القرارات قابلة للعكس.',
    'zone.travel.caution': 'لا تجدول حركات غير قابلة للعكس حول نوافذ السفر وحدها.',
    'zone.travel.rationale': 'الحركة وتغيير السياق قد يحفّزان جودة الخيارات.',
    'zone.wellbeing.label': 'الرفاه',
    'zone.wellbeing.bestUse': 'احمِ التعافي قبل القرارات عالية المخاطر.',
    'zone.wellbeing.caution': 'ليست نصيحة طبية — جدول الراحة كمدخل قرار.',
    'zone.wellbeing.rationale': 'نوافذ التعافي تؤثّر في جودة القرار تحت الحمل.',
  },
  ru: {
    'blind.acts-too-quickly.description': 'Скорость помогает — сделайте паузу, когда ущерб трудно обратить.',
    'blind.acts-too-quickly.label': 'Слишком быстрые действия',
    'blind.acts-too-quickly.mitigation': 'Задайте ограниченное по времени окно решения и обратимое действие по умолчанию.',
    'blind.acts-too-quickly.trigger': 'Высокая неоднозначность с мягким дедлайном',
    'blind.avoids-conflict.description': 'Предпочтение гармонии может отложить нужные трудные разговоры.',
    'blind.avoids-conflict.label': 'Избегание конфликта',
    'blind.avoids-conflict.mitigation': 'Назовите один обязательный разговор и назначьте его до фиксации шага.',
    'blind.avoids-conflict.trigger': 'Межличностное разногласие вокруг решения',
    'blind.context-switching.description': 'Параллельные потоки размывают суждение; группируйте решения по доменам.',
    'blind.context-switching.label': 'Переключение контекста',
    'blind.context-switching.mitigation': 'Группируйте по доменам и закрывайте одно решение до открытия следующего.',
    'blind.context-switching.trigger': 'Несколько открытых решений за день',
    'blind.deferred-follow-through.description': 'Инсайт приходит рано; замкните цикл датированным следующим действием.',
    'blind.deferred-follow-through.label': 'Отложенное доведение',
    'blind.deferred-follow-through.mitigation': 'Прикрепите дату в календаре и владельца к следующему конкретному шагу.',
    'blind.deferred-follow-through.trigger': 'Облегчение после решения',
    'blind.goes-solo-early.description': 'Независимый драйв может пропустить стейкхолдера, снижающего риск.',
    'blind.goes-solo-early.label': 'Слишком ранний соло-режим',
    'blind.goes-solo-early.mitigation': 'Назовите один обязательный разговор и назначьте его до фиксации шага.',
    'blind.goes-solo-early.trigger': 'Межличностное разногласие вокруг решения',
    'blind.overthinks.description': 'Лишний анализ может отложить обратимые шаги, которые учат быстрее.',
    'blind.overthinks.label': 'Переанализ',
    'blind.overthinks.mitigation': 'Задайте ограниченное по времени окно решения и обратимое действие по умолчанию.',
    'blind.overthinks.trigger': 'Высокая неоднозначность с мягким дедлайном',
    'blind.perfectionism.description': 'Стандарты качества растут под давлением; задайте контрольные точки «достаточно хорошо».',
    'blind.perfectionism.label': 'Перфекционизм',
    'blind.perfectionism.mitigation': 'Запишите минимально жизнеспособную планку успеха до дальнейшей доработки.',
    'blind.perfectionism.trigger': 'Публичные или высокозаметные результаты',
    'blind.risk-avoidance.description': 'Осторожность защищает — также запланируйте один контролируемый эксперимент.',
    'blind.risk-avoidance.label': 'Избегание риска',
    'blind.risk-avoidance.mitigation': 'Разделите обратимые пилоты и необратимые обязательства в письменном списке.',
    'blind.risk-avoidance.trigger': 'Варианты с тяжёлым downside',
    'blind.surge-decisions.description': 'Всплески энергии сжимают размышление; «переспите» с необратимыми решениями.',
    'blind.surge-decisions.label': 'Решения на эмоциональном всплеске',
    'blind.surge-decisions.mitigation': 'Разделите обратимые пилоты и необратимые обязательства в письменном списке.',
    'blind.surge-decisions.trigger': 'Дефицит времени + сильная эмоция',
    'communication.approach': 'Сформулируйте решение, критерии и запрос тремя предложениями до обсуждения вариантов.',
    'communication.conflict.align': 'Ищет согласованность; может отложить конфронтацию до давления ставок',
    'communication.conflict.direct': 'Решает вопросы в лоб; может недооценивать эмоциональный темп',
    'communication.env.flexible': 'Гибкие форумы с явными целями',
    'communication.env.prepared': 'Подготовленные 1:1 или сфокусированные малые группы',
    'communication.listen.action': 'Слушает намерение и импульс; резюмирует к действию',
    'communication.listen.analytical': 'Слушает структуру, несоответствия и критерии решения',
    'communication.persuade.ask': 'Сначала ясный запрос и владение',
    'communication.persuade.evidence': 'Сначала доказательства и критерии',
    'communication.persuade.narrative': 'Сначала нарратив и варианты',
    'communication.primary.direct': 'Прямой и ориентированный на результат',
    'communication.primary.relational': 'Реляционный и богатый контекстом',
    'communication.risk.brevity': 'Краткость может пропустить эмоциональный контекст, нужный другим',
    'communication.risk.criteria': 'Неозвученные критерии решения создают ложное согласие',
    'communication.risk.harmony': 'Предпочтение гармонии может похоронить разногласие',
    'conf.blindSpots': 'Метки слепых зон — паттерны риска решений, а не диагнозы.',
    'conf.communication': 'Стиль коммуникации — модель поддержки решений для People и Julia.',
    'conf.comparative': 'Только сравнительные сигналы — не детерминированный прогноз.',
    'conf.complete': 'Профиль построен из полных входов тайминга рождения.',
    'conf.decisionStyle': 'Уверенность стиля решения отслеживает полноту входов тайминга рождения.',
    'conf.decisionStyle.limit': 'Метки стиля — контролируемые enum’ы, а не свободные утверждения о личности.',
    'conf.energy': 'Энергетические диапазоны относительны, а не почасовые прогнозы.',
    'conf.energy.limit': 'Не считайте диапазоны гарантированными пиками производительности.',
    'conf.environment': 'Рекомендации среды поддерживают качество суждения, а не рабочие мандаты.',
    'conf.growth': 'Зоны роста — рекомендации практики решений, а не обещания самопомощи.',
    'conf.leadership': 'Лидерство здесь — влияние и ответственность, а не должность.',
    'conf.learning': 'Предпочтения обучения поддерживают рост навыка решений, а не академические ярлыки.',
    'conf.opportunity': 'Баллы возможностей — относительные силы по зонам, а не прогнозы.',
    'conf.opportunity.limit': 'Не интерпретируйте как уверенность в исходах.',
    'conf.partial': 'Частичный профиль — завершите онбординг, чтобы повысить уверенность.',
    'conf.pressure': 'Паттерны давления — тенденции из тайминга, а не клинические оценки.',
    'conf.strengths': 'Сигналы сильных сторон — сравнительные паттерны, выведенные из тайминга.',
    'conf.work': 'Стиль работы описывает ритм поддержки решений, а не гарантии продуктивности.',
    'decision-style.explanation': 'Основной режим — {primary}, со вторичными наклонами к {secondary}. Рисковая позиция — {risk}; темп обычно {speed}. Выведено из тайминговых якорей рождения и метаданных профиля — сравнительно, не предиктивно.',
    'decision-style.secondary.fallback': 'адаптивная корректировка',
    'energy.explanation.adjusted': ', мягко скорректированные сегодняшним тайминговым баллом.',
    'energy.explanation.base': 'Относительные энергетические диапазоны из тайминговых якорей рождения',
    'energy.explanation.full.adjusted': 'Относительные энергетические диапазоны из тайминговых якорей рождения, мягко скорректированные сегодняшним тайминговым баллом.',
    'energy.explanation.full.noLive': 'Относительные энергетические диапазоны из тайминговых якорей рождения. Живая почасовая точность требует тайминговый движок отдельно.',
    'energy.explanation.noLive': '. Живая почасовая точность требует тайминговый движок отдельно.',
    'energy.recovery.afternoon': 'Сброс поздним днём до вечерних обязательств',
    'energy.recovery.midday': 'Пауза в середине дня между блоками решений',
    'energy.recovery.morning': 'Буфер поздним утром после ранних обязательств',
    'env.collab.high': 'Высокая для крупных решений',
    'env.collab.selective': 'Избирательная консультация',
    'env.distraction.high': 'Высокая',
    'env.distraction.moderate': 'Умеренная',
    'env.info.criteria': 'Критерии и доказательства до обязательства',
    'env.info.options': 'Ясные варианты и обратимый следующий шаг',
    'env.pressure.high': 'Умеренная–высокая',
    'env.pressure.low': 'Низкая–умеренная',
    'env.setting.collaborative': 'Коллаборативный',
    'env.setting.flexible': 'Гибкий',
    'env.setting.quiet': 'Тихий',
    'env.setting.remote': 'Удалённый / контролируемый',
    'env.setting.stable': 'Стабильное рабочее пространство',
    'env.setting.travel': 'Удобный для путешествий',
    'env.setup': 'Тихая или подготовленная малая группа, письменные критерии, один обратимый пилот и жёсткое время обзора.',
    'error.loadFailed': 'Не удалось загрузить профиль персонального интеллекта.',
    'evidence.countOnly': 'Только счётчик — сырая история не встроена в профиль.',
    'evidence.derived': 'Выведено только из доступных тайминговых якорей профиля.',
    'evidence.partial': 'Частичный профиль — недостающие входы снизили уверенность.',
    'growth.blind-spot.area': 'Наблюдение за главной слепой зоной',
    'growth.blind-spot.practice.unnamed': 'Назовите главный риск одним предложением до решения.',
    'growth.blind-spot.reason': 'Паттерн «{label}» проявляется под нагрузкой.',
    'growth.blind-spot.reason.unnamed': 'Безымянный риск замедляет восстановление после решений.',
    'growth.blind-spot.review': 'Раз в две недели',
    'growth.blind-spot.success': 'Одна явная контрольная точка прикреплена к следующему решению с высокими ставками.',
    'growth.conflict.area': 'Практика прямого конфликта',
    'growth.conflict.practice': 'Практикуйте один подготовленный прямой разговор в месяц.',
    'growth.conflict.reason': 'Предпочтение согласованности может отложить необходимое трение.',
    'growth.conflict.review': 'Ежемесячно',
    'growth.conflict.success': 'Заметки решения включают минимум один противоположный ввод.',
    'growth.dissent.area': 'Инакомыслящий ввод',
    'growth.dissent.practice': 'Пригласите одно инакомыслящее мнение до фиксации крупных шагов.',
    'growth.dissent.reason': 'Независимый драйв может упустить стейкхолдеров, снижающих риск.',
    'growth.protected.area': 'Защищённые блоки решений',
    'growth.protected.practice': 'Защитите один блок deep-work решений в дни высоких ставок.',
    'growth.protected.reason': 'Качество суждения падает без непрерывного фокуса.',
    'growth.protected.review': 'Еженедельно',
    'growth.protected.success': 'Календарь показывает помеченный блок решения до крупных звонков.',
    'growth.reversible.area': 'Сначала обратимые обязательства',
    'growth.reversible.practice': 'Определите 48-часовой обратимый эксперимент до любого необратимого обязательства.',
    'growth.reversible.reason': 'Необратимые шаги без пилотов повышают downside.',
    'growth.reversible.review': 'Ежемесячно',
    'growth.reversible.success': 'Каждый крупный лог решения включает шаг пилота и дату.',
    'growth.review.area': 'Привычка обзора решений',
    'growth.review.practice': 'Ежемесячно просматривайте сохранённые решения: что изменилось vs что вы рекомендовали.',
    'growth.review.reason': 'Без обзора рекомендации не складываются в навык.',
    'growth.review.review': 'Ежемесячно',
    'growth.review.success': 'История Vault или Pathfinder показывает датированную заметку обзора.',
    'horizon.balanced': 'Сбалансированный',
    'horizon.long-term': 'Долгосрочный',
    'horizon.near-term': 'Краткосрочный',
    'independence.collaborative': 'Коллаборативный',
    'independence.independent': 'Независимый',
    'independence.selective': 'Избирательный',
    'leadership.development': 'Практикуйте формулировку критериев и следующего владельца в каждом брифе решения, который вы ведёте.',
    'leadership.environment': 'Ясное владение, явные сигналы успеха и пространство для обратимых экспериментов.',
    'leadership.primary.analyst': 'Аналитик',
    'leadership.primary.builder': 'Строитель',
    'leadership.primary.mentor': 'Наставник',
    'leadership.primary.vision': 'Видение-ориентированный',
    'leadership.risk.analysis': 'Задержка анализа при срочности',
    'leadership.risk.conflict': 'Избегание конфликта',
    'leadership.risk.execution': 'Недостаточно специфицированное исполнение',
    'leadership.risk.optimize': 'Чрезмерная оптимизация сборки до выравнивания',
    'leadership.secondary.adaptive': 'Адаптивный',
    'leadership.secondary.operational': 'Операционный',
    'leadership.strength.align': 'Выравнивает общие исходы',
    'leadership.strength.contribution': 'Приглашает вклад',
    'leadership.strength.destination': 'Задаёт направление',
    'leadership.strength.evidence': 'Повышает качество решений доказательствами',
    'leadership.strength.people': 'Развивает людей',
    'leadership.strength.ships': 'Доставляет прогресс',
    'leadership.strength.systems': 'Уточняет системы в движении',
    'leadership.strength.tradeoffs': 'Проясняет компромиссы',
    'learning.barrier.frameworks': 'Сбор рамок без живого применения',
    'learning.barrier.reflection': 'Пропуск рефлексии после экспериментов',
    'learning.method.analytical': 'Аналитический',
    'learning.method.discussion': 'Обсуждение',
    'learning.method.experimentation': 'Экспериментирование',
    'learning.method.practical': 'Практический',
    'learning.method.reading': 'Чтение',
    'learning.method.visual': 'Визуальное картирование',
    'learning.practice': 'Применяйте в течение 48 часов после обучения',
    'learning.processing.models': 'Модели, объясняющие реальные случаи',
    'learning.processing.real': 'Сначала малые реальные версии',
    'learning.recommended': 'Сначала {primary}, затем {secondary}, чтобы проверить понимание.',
    'learning.retention': 'Пересказ или письменная заметка решения после практики',
    'legacy.blind.why': '{description} Смягчение: {mitigation}',
    'legacy.fast.label': 'Быстрый',
    'legacy.fast.why': 'Скорость решения склоняется к быстрой, когда входы ясны.',
    'legacy.patient.label': 'Терпеливый',
    'legacy.patient.why': 'Рисковая ориентация предпочитает обдуманный темп.',
    'legacy.riskBalanced.label': 'Сбалансированный риск',
    'legacy.riskBalanced.why': 'Рисковая ориентация: {risk}.',
    'limit.comparative': 'Только сравнительная поддержка решений.',
    'limit.noLiveTiming': 'Живой тайминговый контекст не был передан при сборке.',
    'pressure.protocol': 'Назовите необратимую часть, сожмите следующий шаг до обратимого действия и решите внутри более сильного энергетического окна с датированной контрольной точкой.',
    'pressure.recovery.default': 'Короткий отход, затем один конкретный следующий шаг, восстанавливает темп.',
    'pressure.recovery.morning': 'Ранние тихие сбросы плюс письменный список приоритетов восстанавливают качество суждения.',
    'pressure.response.action': 'Ускоряется к действию; неоднозначность может ощущаться как потеря импульса.',
    'pressure.response.analytical': 'Сужает фокус и ищет больше данных; срочность может ощущаться как неполная информация.',
    'pressure.risk.action': 'Сжатие размышления повышает риск необратимой ошибки.',
    'pressure.risk.analytical': 'Чрезмерный сбор входов откладывает обратимое обучение.',
    'pressure.trigger.deadlines': 'Жёсткие дедлайны при неполной информации',
    'pressure.trigger.disagreement': 'Межличностное разногласие',
    'pressure.trigger.irreversible': 'Необратимый downside без пути пилота',
    'pressure.trigger.silence': 'Молчание стейкхолдеров при неясном владении',
    'risk.balanced': 'Сбалансированный',
    'risk.bold': 'Смелый',
    'risk.cautious': 'Осторожный',
    'speed.deliberate': 'Обдуманный',
    'speed.fast': 'Быстрый',
    'speed.measured': 'Измеренный',
    'strength.communication.application': 'Сформулируйте критерии решения в коротком брифе до сбора мнений.',
    'strength.communication.description': 'Ясность растёт, когда идеи проговариваются и проверяются с другими.',
    'strength.communication.label': 'Коммуникация',
    'strength.creativity.application': 'Вынудите неочевидный третий вариант до бинарного «взять/оставить».',
    'strength.creativity.description': 'Свежие варианты появляются, когда ограничения явны.',
    'strength.creativity.label': 'Креативность',
    'strength.decision-sequencing.application': 'Требуйте датированный обратимый пилот до любого трудно обратимого обязательства.',
    'strength.decision-sequencing.description': 'Лучше всего работает, когда необратимые шаги следуют за обратимыми пилотами.',
    'strength.decision-sequencing.label': 'Последовательность решений',
    'strength.execution-focus.application': 'Защитите один непрерывный блок для необратимого шага.',
    'strength.execution-focus.description': 'Устойчивые окна концентрации превращают планы в готовый результат.',
    'strength.execution-focus.label': 'Фокус на исполнении',
    'strength.leadership.application': 'Назовите владельца решения и сигнал успеха до открытия дискуссии.',
    'strength.leadership.description': 'Задание направления — естественный режим при ясных целях.',
    'strength.leadership.label': 'Лидерство',
    'strength.learning-speed.application': 'Запустите малую реальную версию варианта, чтобы учиться быстрее теории.',
    'strength.learning-speed.description': 'Быстро осваивает новые рамки, когда ставки реальны.',
    'strength.learning-speed.label': 'Скорость обучения',
    'strength.long-term-planning.application': 'Используйте при ранжировании вариантов по влиянию на 90 дней до вложения капитала или репутации.',
    'strength.long-term-planning.description': 'Строит выбор вокруг многошаговых результатов, а не одного хода.',
    'strength.long-term-planning.label': 'Долгосрочное планирование',
    'strength.negotiation.application': 'Перечислите must-have каждой стороны до торга.',
    'strength.negotiation.description': 'Компромиссы яснее, когда интересы картографированы.',
    'strength.negotiation.label': 'Переговоры',
    'strength.pattern-recognition.application': 'Перед выбором сопоставьте два аналогичных прошлых решения.',
    'strength.pattern-recognition.description': 'Связывает сигналы из разных контекстов до действия.',
    'strength.pattern-recognition.label': 'Распознавание паттернов',
    'strength.systems-thinking.application': 'Набросайте риски зависимостей до оптимизации одного рычага.',
    'strength.systems-thinking.description': 'Видит взаимодействие частей до оптимизации одной.',
    'strength.systems-thinking.label': 'Системное мышление',
    'style.adaptive': 'Адаптивный',
    'style.analytical': 'Аналитический',
    'style.cautious': 'Осторожный',
    'style.collaborative': 'Коллаборативный',
    'style.execution-focused': 'ориентированный на выполнение',
    'style.exploratory': 'Исследовательский',
    'style.intuitive': 'Интуитивный',
    'style.strategic': 'Стратегический',
    'style.decisive': 'Решительный',
    'style.risk-aware': 'Осознающий риск',
    'summary.body': 'Вы принимаете решения в режиме {styles}, с заметными сильными сторонами в {strengthLabels}. Лидерство склоняется к {leadership}, а рабочий ритм предпочитает {work}. Используйте обратимые пилоты перед необратимыми обязательствами и планируйте высокие ставки в более сильных энергетических окнах. Это сравнительные сигналы поддержки решений, а не прогнозы.',
    'work.change.high': 'Высокая — ищет полезную новизну',
    'work.change.measured': 'Измеренная — предпочитает последовательные изменения',
    'work.collab.owner': 'Владельческий',
    'work.collab.team': 'Командно-ориентированный',
    'work.env.deep': 'Блоки с малым числом прерываний для решений с высокими ставками',
    'work.env.flexible': 'Гибкое пространство с чистыми входами решения',
    'work.focus.deep': 'Глубокая работа',
    'work.focus.flexible': 'Гибкое переключение',
    'work.rhythm.frontload': 'Критическую работу вперёд',
    'work.rhythm.lateday': 'Доработка в конце дня',
    'work.rhythm.midday': 'Пики исполнения в середине дня',
    'work.risk.interruptions': 'Прерывания обрушивают качество суждения',
    'work.risk.irreversible': 'Старт необратимой работы до обратимого пилота',
    'work.risk.switching': 'Переключение контекста без группировки',
    'work.structure.adaptive': 'Адаптивная структура',
    'work.structure.plans': 'Структурированные планы',
    'zone.business.label': 'Бизнес',
    'zone.business.bestUse': 'Пилотируйте предложения до полного обязательства.',
    'zone.business.caution': 'Избегайте запусков «всё или ничего» в дни низкой готовности.',
    'zone.business.rationale': 'Паттерн профиля поддерживает генерацию опций и поэтапные запуски.',
    'zone.career.label': 'Карьера',
    'zone.career.bestUse': 'Приоритизируйте один карьерный рычаг с еженедельным обзором.',
    'zone.career.caution': 'Не трактуйте балл как прогноз повышения.',
    'zone.career.rationale': 'Тайминговые якоря поддерживают структурированный прогресс к ясным целям роли.',
    'zone.creativity.label': 'Креативность',
    'zone.creativity.bestUse': 'Вынудите третий вариант до бинарного выбора.',
    'zone.creativity.caution': 'Новизна без контрольных точек повышает риск исполнения.',
    'zone.creativity.rationale': 'Креативный диапазон поддерживает альтернативное фреймирование под ограничениями.',
    'zone.leadership.label': 'Лидерство',
    'zone.leadership.bestUse': 'Ведите решения, называя критерии и следующего владельца.',
    'zone.leadership.caution': 'Лидерство здесь — влияние, а не должность.',
    'zone.leadership.rationale': 'Паттерны влияния предпочитают прояснение владения и исходов.',
    'zone.learning.label': 'Обучение',
    'zone.learning.bestUse': 'Соедините учёбу с малым прикладным экспериментом.',
    'zone.learning.caution': 'Завершение всё ещё зависит от дизайна практики.',
    'zone.learning.rationale': 'Сигналы скорости обучения / паттернов поддерживают освоение навыков.',
    'zone.money.label': 'Деньги',
    'zone.money.bestUse': 'Задайте лимиты downside до аллокации.',
    'zone.money.caution': 'Балл сравнительный — не рыночный совет.',
    'zone.money.rationale': 'Аналитический диапазон поддерживает взвешенные решения о капитале.',
    'zone.networking.label': 'Нетворкинг',
    'zone.networking.bestUse': 'Запросите одно инакомыслящее мнение до крупных фиксаций.',
    'zone.networking.caution': 'Объём контактов ≠ качество решения.',
    'zone.networking.rationale': 'Коллаборативный уклон улучшает сигнал от доверенных коллег.',
    'zone.relationships.label': 'Отношения',
    'zone.relationships.bestUse': 'Планируйте важные разговоры в более сильных энергетических окнах.',
    'zone.relationships.caution': 'Не прогноз исхода отношений.',
    'zone.relationships.rationale': 'Реляционные решения выигрывают от окон ясности коммуникации.',
    'zone.travel.label': 'Путешествия',
    'zone.travel.bestUse': 'Используйте путешествия для исследования, когда решения обратимы.',
    'zone.travel.caution': 'Не планируйте необратимые шаги только вокруг окон путешествий.',
    'zone.travel.rationale': 'Движение и смена контекста могут стимулировать качество опций.',
    'zone.wellbeing.label': 'Благополучие',
    'zone.wellbeing.bestUse': 'Защитите восстановление до решений с высокими ставками.',
    'zone.wellbeing.caution': 'Не медицинский совет — планируйте отдых как вход решения.',
    'zone.wellbeing.rationale': 'Окна восстановления влияют на качество решений под нагрузкой.',
  },
};

function interpolate(
  template: string,
  vars?: Record<string, string | number>
): string {
  if (!vars) return template;
  return template.replace(/\{([a-zA-Z0-9_]+)\}/g, (match, name: string) => {
    const value = vars[name];
    return value == null ? match : String(value);
  });
}

/**
 * Resolve intelligence prose by locale + key.
 * Never silently falls back to English for fa/ar/ru.
 */
export function iq(
  locale: AppLang,
  key: string,
  vars?: Record<string, string | number>
): string {
  const local = PROSE[locale]?.[key];
  if (local != null) return interpolate(local, vars);
  if (locale !== 'en') return INTELLIGENCE_UNAVAILABLE[locale];
  const en = PROSE.en?.[key];
  if (en != null) return interpolate(en, vars);
  return key;
}

const STYLE_PREFIXES = ['style.', 'risk.', 'speed.'] as const;

/** Canonical decision-style IDs that must never appear raw in fa/ar/ru prose. */
export const DECISION_STYLE_TOKEN_IDS = [
  'strategic',
  'analytical',
  'adaptive',
  'intuitive',
  'collaborative',
  'execution-focused',
  'cautious',
  'exploratory',
  'decisive',
  'risk-aware',
] as const;

/** Map known decision-style / risk / speed enum tokens to localized labels. */
export function localizeStyleToken(token: string, locale: AppLang): string {
  // Accept kebab ids, snake_case, and Title Case / spaced English labels.
  const normalized = token.trim().toLowerCase().replace(/[_\s]+/g, '-');
  for (const prefix of STYLE_PREFIXES) {
    const key = `${prefix}${normalized}`;
    if (PROSE.en[key] != null) {
      return iq(locale, key);
    }
  }
  // Also accept already-prefixed keys
  if (
    normalized.startsWith('style.') ||
    normalized.startsWith('risk.') ||
    normalized.startsWith('speed.')
  ) {
    if (PROSE.en[normalized] != null) return iq(locale, normalized);
  }
  // Non-en: never leak raw Latin kebab/snake style ids into UI prose
  if (locale !== 'en' && /^[a-z][a-z0-9-]*$/i.test(normalized)) {
    return iq(locale, 'style.adaptive');
  }
  return token;
}

/**
 * Replace known English decision-style tokens inside prose with localized labels.
 * Structural IDs stay unchanged elsewhere; this is presentation-only.
 */
export function localizeStyleTokensInText(text: string, locale: AppLang): string {
  if (!text || locale === 'en') return text;
  let out = text;
  for (const id of DECISION_STYLE_TOKEN_IDS) {
    const label = localizeStyleToken(id, locale);
    const escaped = id.replace(/-/g, '[-_\\s]?');
    out = out.replace(new RegExp(`\\b${escaped}\\b`, 'gi'), label);
  }
  return out;
}

/** Join style IDs into a natural localized list for sentence embedding. */
export function formatLocalizedStyleList(
  styles: string[],
  locale: AppLang,
  copy: (key: string) => string
): string {
  const labels = styles
    .slice(0, 3)
    .map((s) => localizeStyleToken(s, locale))
    .filter(Boolean);
  if (labels.length === 0) return copy('analysis.personalFit.styles.available');
  if (labels.length === 1) return labels[0]!;
  const sep = copy('analysis.personalFit.styles.listSep');
  const and = copy('analysis.personalFit.styles.listAnd');
  if (labels.length === 2) return `${labels[0]}${and}${labels[1]}`;
  return `${labels.slice(0, -1).join(sep)}${and}${labels[labels.length - 1]}`;
}
